ERROR_SYNC_REGIONS = "ERROR_SYNC_REGIONS"
ERROR_SYNC_ZONES = "ERROR_SYNC_ZONES"
ERROR_SYNC_IMAGES = "ERROR_SYNC_IMAGES"
ERROR_SYNC_INSTANCE_PROFILES = "ERROR_SYNC_INSTANCE_PROFILES"
ERROR_SYNC_VOLUME_PROFILES = "ERROR_SYNC_VOLUME_PROFILES"
ERROR_SYNC_RESOURCE_GROUPS = "ERROR_SYNC_RESOURCE_GROUPS"
ERROR_SYNC_ADDRESS_PREFIXES = "ERROR_SYNC_ADDRESS_PREFIXES"
ERROR_SYNC_COS_BUCKETS = "ERROR_SYNC_COS_BUCKETS"

FLOATING_IP_NAME = "f{}-floating-ip-{}"

INST_START = 'start'
INST_CREATING_IMAGE_TEMPLATE = 'creating_image_template'
INST_EXPORT_COS = 'export_cos'
INST_IMAGE_CONVERTING = 'qcow2_image_converting'
INST_CREATING_CUSTOM_IMAGE = 'creating_custom_image'
INST_INSTANCE_CREATING = 'creating_instance'

PROVISIONING = "provisioning"
VALIDATION = "validation"
