"""empty message

Revision ID: 02dd0fd8b33a
Revises: b52331519258
Create Date: 2020-02-12 08:34:14.259518

"""

# revision identifiers, used by Alembic.
revision = '02dd0fd8b33a'
down_revision = 'b52331519258'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instance_profiles', 'family',
               existing_type=mysql.ENUM('BALANCED', 'CPU', 'MEMORY'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instance_profiles', 'family',
               existing_type=mysql.ENUM('BALANCED', 'CPU', 'MEMORY'),
               nullable=False)
    # ### end Alembic commands ###