"""empty message

Revision ID: 066047793788
Revises: 4a931491a5de
Create Date: 2021-05-07 18:59:49.316674

"""

# revision identifiers, used by Alembic.
from doosra.models import IBMInstanceProfile
from doosra import db as doosradb

revision = '066047793788'
down_revision = '4a931491a5de'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

new_type = sa.Enum("BALANCED", "COMPUTE", "MEMORY", "GPU", "HIGH-MEMORY", name='family')
old_type = sa.Enum("BALANCED", "COMPUTE", "MEMORY", "GPU", name='family')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instance_profiles', u'family', type_=new_type,
                    existing_type=old_type)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for profile in IBMInstanceProfile.query.filter_by(family="HIGH-MEMORY").all():
        doosradb.session.delete(profile)
        doosradb.session.commit()
    op.alter_column('ibm_instance_profiles', u'family', type_=old_type,
                    existing_type=new_type)
    # ### end Alembic commands ###

