"""empty message

Revision ID: 0846512ef607
Revises: 555f10688250
Create Date: 2020-03-04 10:55:05.129189

"""

# revision identifiers, used by Alembic.
revision = '0846512ef607'
down_revision = '555f10688250'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_credentials', 'access_token',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.add_column('ibm_tasks', sa.Column('request_payload', mysql.MEDIUMTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_tasks', 'request_payload')
    op.alter_column('ibm_credentials', 'access_token',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###