"""empty message

Revision ID: 0e33ef5092d7
Revises: c659df275c1c
Create Date: 2020-08-11 12:06:31.347677

"""

# revision identifiers, used by Alembic.
revision = '0e33ef5092d7'
down_revision = 'c659df275c1c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transit_gateway_connections_ibfk_2', 'transit_gateway_connections', type_='foreignkey')
    op.create_foreign_key('transit_gw_connection_ibm_vpc_ibfk_1', 'transit_gateway_connections', 'ibm_vpc_networks', ['vpc_id'], ['id'], ondelete='CASCADE')
    op.alter_column('transit_gateways', 'cloud_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transit_gateways', 'cloud_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.drop_constraint('transit_gw_connection_ibm_vpc_ibfk_1', 'transit_gateway_connections', type_='foreignkey')
    op.create_foreign_key('transit_gateway_connections_ibfk_2', 'transit_gateway_connections', 'ibm_vpc_networks', ['vpc_id'], ['id'])
    # ### end Alembic commands ###
