"""empty message

Revision ID: 123169178ee7
Revises: 48f3f40366c5
Create Date: 2020-02-27 07:13:34.640109

"""

# revision identifiers, used by Alembic.
revision = '123169178ee7'
down_revision = '48f3f40366c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_volumes', sa.Column('status', sa.String(length=50), nullable=False))
    op.create_unique_constraint('uix_ibm_volumes_name_region_cloud_id', 'ibm_volumes', ['name', 'region', 'cloud_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_ibm_volumes_name_region_cloud_id', 'ibm_volumes', type_='unique')
    op.drop_column('ibm_volumes', 'status')
    # ### end Alembic commands ###