"""empty message

Revision ID: 151634748d1e
Revises: 549b486f872c
Create Date: 2019-07-31 07:42:12.040404

"""

# revision identifiers, used by Alembic.
revision = '151634748d1e'
down_revision = '549b486f872c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gcp_instance_groups_instances',
    sa.Column('instance_id', sa.String(length=32), nullable=False),
    sa.Column('instance_group_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instance_group_id'], ['gcp_instance_groups.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['gcp_instances.id'], ),
    sa.PrimaryKeyConstraint('instance_id', 'instance_group_id')
    )
    op.drop_constraint('instance_instance_groups_ibfk_1', 'gcp_instances', type_='foreignkey')
    op.drop_column('gcp_instances', 'instance_group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gcp_instances', sa.Column('instance_group_id', mysql.VARCHAR(length=32), nullable=True))
    op.create_foreign_key('instance_instance_groups_ibfk_1', 'gcp_instances', 'gcp_instance_groups', ['instance_group_id'], ['id'])
    op.drop_table('gcp_instance_groups_instances')
    # ### end Alembic commands ###