"""empty message

Revision ID: 17923ffd701a
Revises: a0fa679811dd
Create Date: 2020-01-15 12:06:55.920814

"""

# revision identifiers, used by Alembic.
revision = '17923ffd701a'
down_revision = 'a0fa679811dd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_volumes', 'region',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_volumes', 'region',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###