"""empty message

Revision ID: 19d2ee37e932
Revises: cc720cfa9176
Create Date: 2019-04-17 08:52:24.599551

"""

# revision identifiers, used by Alembic.
revision = '19d2ee37e932'
down_revision = 'cc720cfa9176'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gcp_cloud_projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.Column('user_project_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['gcp_clouds.id'], ),
    sa.ForeignKeyConstraint(['user_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gcp_tasks',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('result',sa.Text(), nullable=True),
    sa.Column('resource_id', sa.String(length=32), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cloud_id'], ['gcp_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gcp_vpc_networks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('auto_create_subnetworks', sa.Boolean(), nullable=True),
    sa.Column('routing_mode', sa.String(length=255), nullable=False),
    sa.Column('cloud_project_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_project_id'], ['gcp_cloud_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gcp_subnets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('ip_cidr_range', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('enable_flow_logs', sa.Boolean(), nullable=False),
    sa.Column('private_google_access', sa.Boolean(), nullable=False),
    sa.Column('vpc_network_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['vpc_network_id'], ['gcp_vpc_networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gcp_secondary_ip_ranges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ip_cidr_range', sa.String(length=255), nullable=False),
    sa.Column('subnet_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['subnet_id'], ['gcp_subnets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('gcp_clouds', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gcp_clouds', 'last_synced_at')
    op.drop_table('gcp_secondary_ip_ranges')
    op.drop_table('gcp_subnets')
    op.drop_table('gcp_vpc_networks')
    op.drop_table('gcp_tasks')
    op.drop_table('gcp_cloud_projects')
    # ### end Alembic commands ###