"""empty message

Revision ID: d87cdc7e9f1b
Revises: d87cdc7e9f1b
Create Date: 2019-09-03 10:05:36.213928

"""

# revision identifiers, used by Alembic.
revision = '1df974311bb'
down_revision = 'd87cdc7e9f1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_vpc_routes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('href', sa.String(length=300), nullable=True),
    sa.Column('lifecycle_state', sa.Enum('deleted', 'deleting', 'failed', 'pending', 'stable', 'updating', 'waiting'), nullable=True),
    sa.Column('destination', sa.String(length=32), nullable=True),
    sa.Column('next_hop_address', sa.String(length=16), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_vpc_routes')
    # ### end Alembic commands ###
