"""empty message

Revision ID: 1ea6dae600a2
Revises: 60bed28caaa5
Create Date: 2020-05-19 15:46:11.237815

"""

# revision identifiers, used by Alembic.
revision = '1ea6dae600a2'
down_revision = '60bed28caaa5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('_status', sa.Enum('IN_PROGRESS', 'COMPLETED'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', '_status')
    # ### end Alembic commands ###