"""
Revision ID: 2025f2a3513a
Revises: 66e6d4c324dc
Create Date: 2020-03-16 19:13:09.081650
"""

# revision identifiers, used by Alembic.
revision = '2025f2a3513a'
down_revision = '66e6d4c324dc'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'request_metadata',
                    existing_type=sa.Text(),
                    type_=mysql.LONGTEXT())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'request_metadata',
                    existing_type=mysql.LONGTEXT(),
                    type_=sa.Text())
