"""empty message

Revision ID: 230c8731fc81
Revises: e0eb9d545e41
Create Date: 2020-03-03 08:45:35.431302

"""

# revision identifiers, used by Alembic.
revision = '230c8731fc81'
down_revision = 'e0eb9d545e41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_instance_profiles', sa.Column('architecture', sa.Enum('power', 'amd64'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_instance_profiles', 'architecture')
    # ### end Alembic commands ###