"""empty message

Revision ID: 2621a49ffb6e
Revises: 76a764306ba0
Create Date: 2019-07-15 06:46:25.830313

"""

# revision identifiers, used by Alembic.
revision = '2621a49ffb6e'
down_revision = '76a764306ba0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_security_group_rules', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('ibm_security_group_rules', 'code',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('ibm_security_group_rules', 'port_max',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('ibm_security_group_rules', 'port_min',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('ibm_security_group_rules', 'type',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.add_column('ibm_security_groups', sa.Column('cloud_id', sa.String(length=32), nullable=False))
    op.add_column('ibm_security_groups', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.add_column('ibm_security_groups', sa.Column('resource_group_id', sa.String(length=32), nullable=True))
    op.add_column('ibm_security_groups', sa.Column('status', sa.String(length=50), nullable=False))
    op.create_foreign_key("ibm_security_group_clouds_ibfk_2", 'ibm_security_groups', 'ibm_clouds', ['cloud_id'], ['id'])
    op.create_foreign_key("ibm_security_group_resource_g_ibfk_1", 'ibm_security_groups', 'ibm_resource_groups', ['resource_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ibm_security_group_resource_g_ibfk_1", 'ibm_security_groups', type_='foreignkey')
    op.drop_constraint("ibm_security_group_clouds_ibfk_2", 'ibm_security_groups', type_='foreignkey')
    op.drop_column('ibm_security_groups', 'status')
    op.drop_column('ibm_security_groups', 'resource_group_id')
    op.drop_column('ibm_security_groups', 'is_default')
    op.drop_column('ibm_security_groups', 'cloud_id')
    op.alter_column('ibm_security_group_rules', 'type',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('ibm_security_group_rules', 'port_min',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('ibm_security_group_rules', 'port_max',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('ibm_security_group_rules', 'code',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('ibm_security_group_rules', 'status')
    # ### end Alembic commands ###