"""empty message

Revision ID: 2ce998b4b593
Revises: d6b7e72c1a61
Create Date: 2019-04-17 11:41:01.569390

"""

# revision identifiers, used by Alembic.
revision = '2ce998b4b593'
down_revision = 'd6b7e72c1a61'

from alembic import op
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gcp_tasks', 'result',
                    existing_type=mysql.TEXT(),
                    type_=mysql.MEDIUMTEXT())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gcp_tasks', 'result',
                    existing_type=mysql.MEDIUMTEXT(),
                    type_=mysql.TEXT())
    # ### end Alembic commands ###
