"""empty message

Revision ID: 300eaae04155
Revises: f8a4fc6ff994
Create Date: 2020-01-16 14:32:36.362056

"""

# revision identifiers, used by Alembic.
revision = '300eaae04155'
down_revision = 'f8a4fc6ff994'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_ike_policy', 'encryption_algorithm',
               existing_type=mysql.ENUM('3des', 'aes128', 'aes256'),
               type_=sa.Enum('triple_des', 'aes128', 'aes256'),
               existing_nullable=True)
    op.alter_column('ibm_ipsec_policy', 'encryption_algorithm',
               existing_type=mysql.ENUM('3des', 'aes128', 'aes256'),
               type_=sa.Enum('triple_des', 'aes128', 'aes256'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_ipsec_policy', 'encryption_algorithm',
               existing_type=sa.Enum('triple_des', 'aes128', 'aes256'),
               type_=mysql.ENUM('3des', 'aes128', 'aes256'),
               existing_nullable=False)
    op.alter_column('ibm_ike_policy', 'encryption_algorithm',
               existing_type=sa.Enum('triple_des', 'aes128', 'aes256'),
               type_=mysql.ENUM('3des', 'aes128', 'aes256'),
               existing_nullable=True)
    # ### end Alembic commands ###