"""empty message

Revision ID: 344bec98dcb2
Revises: 4be84df9dff0
Create Date: 2019-04-18 11:53:03.844840

"""

# revision identifiers, used by Alembic.
revision = '344bec98dcb2'
down_revision = '4be84df9dff0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gcp_firewall_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target_tags', sa.Text(), nullable=True),
    sa.Column('ip_ranges', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('vpc_network_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['vpc_network_id'], ['gcp_vpc_networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gcp_ip_protocols',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('protocol', sa.String(length=255), nullable=False),
    sa.Column('ports', sa.Text(), nullable=True),
    sa.Column('firewall_rule_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['firewall_rule_id'], ['gcp_firewall_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gcp_ip_protocols')
    op.drop_table('gcp_firewall_rules')
    # ### end Alembic commands ###