"""empty message

Revision ID: 3758d5c41eab
Revises: fa0aafff5df2
Create Date: 2020-05-10 18:09:47.610632

"""

# revision identifiers, used by Alembic.
revision = '3758d5c41eab'
down_revision = 'fa0aafff5df2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_clouds', sa.Column('group_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_clouds', 'group_id')
    # ### end Alembic commands ###