"""empty message

Revision ID: 38b75ba45092
Revises: cd4b2d736df0
Create Date: 2021-01-06 12:02:03.505312

"""

# revision identifiers, used by Alembic.
revision = '38b75ba45092'
down_revision = 'cd4b2d736df0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_tasks', sa.Column('resource_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_tasks', 'resource_id')
    # ### end Alembic commands ###
