"""empty message

Revision ID: 3af8bf38d301
Revises: 46da67bd1c96
Create Date: 2020-07-08 12:03:49.039896

"""

# revision identifiers, used by Alembic.
revision = '3af8bf38d301'
down_revision = '46da67bd1c96'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instances_tasks', 'classical_instance_id', existing_type=sa.String(length=32),
                    type_=sa.Integer())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instances_tasks', 'classical_instance_id', existing_type=sa.Integer(),
                    type_=sa.String(length=32))
    # ### end Alembic commands ###

