"""empty message

Revision ID: 3dd18334c775
Revises: 831de097401b
Create Date: 2021-09-18 10:34:53.179233

"""

# revision identifiers, used by Alembic.
revision = '3dd18334c775'
down_revision = '831de097401b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_instances', sa.Column('nas_migration_enabled', sa.Boolean(), nullable=False))
    op.drop_column('ibm_instances_tasks', 'nas_mig_user_data_script')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_instances_tasks', sa.Column('nas_mig_user_data_script', mysql.TEXT(), nullable=True))
    op.drop_column('ibm_instances', 'nas_migration_enabled')
    # ### end Alembic commands ###