"""empty message

Revision ID: 40284a6c9e37
Revises: f7a6326f8d96
Create Date: 2021-10-05 13:05:35.312261

"""

# revision identifiers, used by Alembic.
revision = '40284a6c9e37'
down_revision = 'f7a6326f8d96'

from alembic import op
import sqlalchemy as sa

new_type = sa.Enum("AUTHENTICATING", "INVALID", "VALID", "DELETING", "ERROR_DUPLICATE_RESOURCE_GROUPS")
old_type = sa.String(50)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_clouds', u'status', type_=new_type,
                    existing_type=old_type, existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_clouds', u'status', type_=old_type,
                    existing_type=new_type, existing_nullable=False)
    # ### end Alembic commands ###
