"""empty message

Revision ID: 404ba908592e
Revises: 04ec3c8ecbdd
Create Date: 2020-02-22 17:34:28.146050

"""

# revision identifiers, used by Alembic.
revision = '404ba908592e'
down_revision = '04ec3c8ecbdd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_tasks', sa.Column('trace_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_tasks', 'trace_id')
    # ### end Alembic commands ###