"""empty message

Revision ID: 46da67bd1c96
Revises: a6616e7bf93a
Create Date: 2020-07-01 11:40:24.585336

"""

# revision identifiers, used by Alembic.
revision = '46da67bd1c96'
down_revision = 'a6616e7bf93a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('finger_print', sa.String(length=100), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('device_info', sa.JSON(), nullable=False),
    sa.Column('session_token', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('trusted', 'untrusted'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('auth_tokens', sa.Column('data', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_tokens', 'data')
    op.drop_table('devices')
    # ### end Alembic commands ###

