"""empty message

Revision ID: 48f3f40366c5
Revises: 404ba908592e
Create Date: 2020-02-25 08:42:46.330038

"""

# revision identifiers, used by Alembic.
revision = '48f3f40366c5'
down_revision = '404ba908592e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_instances', sa.Column('cos_bucket_name', sa.String(length=500), nullable=True))
    op.add_column('ibm_instances', sa.Column('is_image_migration', sa.Boolean(), nullable=False))
    op.add_column('ibm_instances', sa.Column('is_volume_migration', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_instances', 'is_volume_migration')
    op.drop_column('ibm_instances', 'is_image_migration')
    op.drop_column('ibm_instances', 'cos_bucket_name')
    # ### end Alembic commands ###