"""empty message

Revision ID: 4a931491a5de
Revises: 38b75ba45092
Create Date: 2021-02-24 14:25:57.799771

"""

# revision identifiers, used by Alembic.
revision = '4a931491a5de'
down_revision = '38b75ba45092'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instances_tasks', 'image_location',
               existing_type=mysql.ENUM('classical_vsi', 'classical_image', 'cos_vhd', 'cos_qcow2', 'custom_image', 'public_image'),
               type_=mysql.ENUM('classical_vsi', 'classical_image', 'cos_vhd', 'cos_vmdk', 'cos_qcow2', 'custom_image', 'public_image'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instances_tasks', 'image_location',
               existing_type=mysql.ENUM('classical_vsi', 'classical_image', 'cos_vhd', 'cos_vmdk', 'cos_qcow2', 'custom_image', 'public_image'),
               type_=mysql.ENUM('classical_vsi', 'classical_image', 'cos_vhd', 'cos_qcow2', 'custom_image', 'public_image'),
               nullable=False)
    # ### end Alembic commands ###
