"""empty message

Revision ID: 4be84df9dff0
Revises: eb61b85fb1f5
Create Date: 2019-04-29 11:03:56.430115

"""

# revision identifiers, used by Alembic.
revision = '4be84df9dff0'
down_revision = 'eb61b85fb1f5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instance_disks', 'mode',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instance_disks', 'mode',
               existing_type=sa.String(length=255),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###