"""empty message

Revision ID: 4c1a1ff152a7
Revises: 8adb390b00ec
Create Date: 2019-08-17 13:42:50.209184

"""

# revision identifiers, used by Alembic.
revision = '4c1a1ff152a7'
down_revision = '8adb390b00ec'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_load_balancers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('private_ips', sa.Text(), nullable=True),
    sa.Column('public_ips', sa.Text(), nullable=True),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_pools',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('session_persistence', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('load_balancer_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['load_balancer_id'], ['ibm_load_balancers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_health_checks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('url_path', sa.String(length=255), nullable=True),
    sa.Column('pool_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['ibm_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_listeners',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('crn', sa.String(length=255), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('load_balancer_id', sa.String(length=32), nullable=False),
    sa.Column('pool_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['load_balancer_id'], ['ibm_load_balancers.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['ibm_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_load_balancer_subnets',
    sa.Column('load_balancer_id', sa.String(length=32), nullable=False),
    sa.Column('subnets_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['load_balancer_id'], ['ibm_load_balancers.id'], ),
    sa.ForeignKeyConstraint(['subnets_id'], ['ibm_subnets.id'], ),
    sa.PrimaryKeyConstraint('load_balancer_id', 'subnets_id')
    )
    op.create_table('ibm_pool_members',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('pool_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['ibm_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ibm_instances', sa.Column('pool_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('instance_pool_ibfk_1', 'ibm_instances', 'ibm_pool_members', ['pool_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('instance_pool_ibfk_1', 'ibm_instances', type_='foreignkey')
    op.drop_column('ibm_instances', 'pool_id')
    op.drop_table('ibm_pool_members')
    op.drop_table('ibm_load_balancer_subnets')
    op.drop_table('ibm_listeners')
    op.drop_table('ibm_health_checks')
    op.drop_table('ibm_pools')
    op.drop_table('ibm_load_balancers')
    # ### end Alembic commands ###