"""empty message

Revision ID: 4fbd4b070e08
Revises: f94bd2833bf0
Create Date: 2019-11-04 10:04:07.243717

"""

# revision identifiers, used by Alembic.
revision = '4fbd4b070e08'
down_revision = 'f94bd2833bf0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('migration_tasks', 'config_filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migration_tasks', sa.Column('config_filename', mysql.VARCHAR(length=36), nullable=False))
    # ### end Alembic commands ###