"""empty message

Revision ID: 533866308548
Revises: 4fbd4b070e08
Create Date: 2019-11-13 10:57:09.736108

"""

# revision identifiers, used by Alembic.
revision = '533866308548'
down_revision = '4fbd4b070e08'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migration_tasks', sa.Column('result', mysql.MEDIUMTEXT(), nullable=True))
    op.drop_column('migration_tasks', 'ported_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migration_tasks', sa.Column('ported_schema', mysql.MEDIUMTEXT(), nullable=True))
    op.drop_column('migration_tasks', 'result')
    # ### end Alembic commands ###