"""empty message

Revision ID: 549b486f872c
Revises: 10b3582f4549
Create Date: 2019-07-29 13:39:05.908839

"""

# revision identifiers, used by Alembic.
revision = '549b486f872c'
down_revision = '10b3582f4549'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_images',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('architecture', sa.String(length=255), nullable=True),
    sa.Column('os_name', sa.String(length=255), nullable=True),
    sa.Column('os_version', sa.String(length=255), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'public'), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_instance_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('family', sa.Enum('BALANCED', 'CPU', 'MEMORY'), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_volume_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('generation', sa.String(length=255), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_ssh_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('rsa'), nullable=False),
    sa.Column('public_key', sa.String(length=1024), nullable=True),
    sa.Column('finger_print', sa.String(length=512), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_instances',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('zone', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_data', sa.Text(), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.Column('instance_profile_id', sa.String(length=32), nullable=False),
    sa.Column('image_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['ibm_images.id'], ),
    sa.ForeignKeyConstraint(['instance_profile_id'], ['ibm_instance_profiles.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_instance_keys',
    sa.Column('instance_id', sa.String(length=32), nullable=False),
    sa.Column('key_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['ibm_instances.id'], ),
    sa.ForeignKeyConstraint(['key_id'], ['ibm_ssh_keys.id'], ),
    sa.PrimaryKeyConstraint('instance_id', 'key_id')
    )
    op.create_table('ibm_volume_attachments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('instance_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['ibm_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_network_interfaces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('private_ip', sa.String(length=255), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('subnet_id', sa.String(length=32), nullable=True),
    sa.Column('instance_id', sa.String(length=32), nullable=False),
    sa.Column('security_group_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['ibm_instances.id'], ),
    sa.ForeignKeyConstraint(['security_group_id'], ['ibm_security_groups.id'], ),
    sa.ForeignKeyConstraint(['subnet_id'], ['ibm_subnets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_volumes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('zone', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('encryption', sa.String(length=255), nullable=True),
    sa.Column('iops', sa.Integer(), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.Column('volume_profile_id', sa.String(length=32), nullable=False),
    sa.Column('volume_attachment_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['volume_attachment_id'], ['ibm_volume_attachments.id'], ),
    sa.ForeignKeyConstraint(['volume_profile_id'], ['ibm_volume_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ibm_floating_ips', sa.Column('network_interface_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('floating_ip_itf_ibfk_1', 'ibm_floating_ips', 'ibm_network_interfaces', ['network_interface_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('floating_ip_itf_ibfk_1', 'ibm_floating_ips', type_='foreignkey')
    op.drop_column('ibm_floating_ips', 'network_interface_id')
    op.drop_table('ibm_network_interfaces')
    op.drop_table('ibm_volume_attachments')
    op.drop_table('ibm_instance_keys')
    op.drop_table('ibm_instances')
    op.drop_table('ibm_ssh_keys')
    op.drop_table('ibm_volume_profiles')
    op.drop_table('ibm_instance_profiles')
    op.drop_table('ibm_images')
    # ### end Alembic commands ###