"""empty message

Revision ID: 555f10688250
Revises: 230c8731fc81
Create Date: 2020-03-03 17:38:44.196214

"""

# revision identifiers, used by Alembic.
revision = '555f10688250'
down_revision = '230c8731fc81'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_credentials', 'access_token',
                    existing_type=sa.String(length=2000),
                    type_=sa.Text(),
                    existing_nullable=True)
    op.alter_column('ibm_credentials', 'refresh_token',
                    existing_type=sa.String(length=2000),
                    type_=sa.Text(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_credentials', 'access_token',
               existing_type=sa.Text(),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('ibm_credentials', 'refresh_token',
                    existing_type=sa.Text(),
                    type_=sa.String(length=2000),
                    existing_nullable=True)
    # ### end Alembic commands ###