"""empty message

Revision ID: 5888f5b26636
Revises: 40284a6c9e37
Create Date: 2021-10-14 16:07:00.941534

"""

# revision identifiers, used by Alembic.
revision = '5888f5b26636'
down_revision = '40284a6c9e37'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kubernetes_clusters', sa.Column('is_workspace', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kubernetes_clusters', 'is_workspace')
    # ### end Alembic commands ###
