"""empty message

Revision ID: 5c581f12d900
Revises: edc46b0cc9ec
Create Date: 2021-07-16 10:15:41.602550

"""

# revision identifiers, used by Alembic.
revision = '5c581f12d900'
down_revision = 'edc46b0cc9ec'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_history')
    op.drop_table('tokens')
    op.alter_column('ibm_instances_tasks', 'status',
               existing_type=mysql.ENUM('IN_PROGRESS', 'FAILED', 'SUCCESS'),
               nullable=False)
    op.drop_index('name', table_name='projects')
    op.drop_column('projects', 'name')
    op.drop_column('users', 'name')
    op.drop_column('users', 'registered_on')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'confirmed_at_by_admin')
    op.drop_column('users', 'last_logged_in_at')
    op.drop_column('users', 'confirmed_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed_at', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('last_logged_in_at', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('confirmed_at_by_admin', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('registered_on', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('projects', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.create_index('name', 'projects', ['name'], unique=True)
    op.alter_column('ibm_instances_tasks', 'status',
               existing_type=mysql.ENUM('IN_PROGRESS', 'FAILED', 'SUCCESS'),
               nullable=True)
    op.create_table('tokens',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('issued_at', mysql.DATETIME(), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tokens_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('password_history',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('last_updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='password_history_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
