"""empty message

Revision ID: 5d7cf84af732
Revises: 8674a848e57d
Create Date: 2021-08-17 13:50:42.661224

"""

# revision identifiers, used by Alembic.
revision = '5d7cf84af732'
down_revision = '8674a848e57d'

from alembic import op
import sqlalchemy as sa

new_type = sa.Enum("power", "amd64", "s390x", name='architecture')
old_type = sa.Enum("power", "amd64", name='architecture')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instance_profiles', u'architecture', type_=new_type,
                    existing_type=old_type)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instance_profiles', u'architecture', type_=old_type,
                    existing_type=new_type)
    # ### end Alembic commands ###

