"""empty message

Revision ID: 60bed28caaa5
Revises: ecc04f98a4a3
Create Date: 2020-05-17 09:12:06.258500

"""

# revision identifiers, used by Alembic.
revision = '60bed28caaa5'
down_revision = 'ecc04f98a4a3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secondary_volume_migration_tasks', 'status',
               existing_type=mysql.ENUM('IN_PROGRESS','FAILED','SUCCESS','CREATED','BACKGROUND', 'PENDING'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secondary_volume_migration_tasks', 'status',
               existing_type=mysql.ENUM('IN_PROGRESS','FAILED','SUCCESS','CREATED','BACKGROUND'),
               nullable=False)
    # ### end Alembic commands ###


