"""empty message

Revision ID: 61e36a2dc20a
Revises: 4c1a1ff152a7
Create Date: 2019-08-22 06:29:00.497244

"""

# revision identifiers, used by Alembic.
revision = '61e36a2dc20a'
down_revision = '4c1a1ff152a7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('instance_pool_ibfk_1', 'ibm_instances', type_='foreignkey')
    op.drop_column('ibm_instances', 'pool_id')
    op.add_column('ibm_pool_members', sa.Column('instance_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('ibm_pool_mem_instance_ibfk_1', 'ibm_pool_members', 'ibm_instances', ['instance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ibm_pool_mem_instance_ibfk_1', 'ibm_pool_members', type_='foreignkey')
    op.drop_column('ibm_pool_members', 'instance_id')
    op.add_column('ibm_instances', sa.Column('pool_id', mysql.VARCHAR(length=32), nullable=True))
    op.create_foreign_key('instance_pool_ibfk_1', 'ibm_instances', 'ibm_pool_members', ['pool_id'], ['id'])
    # ### end Alembic commands ###
