"""empty message

Revision ID: 64c98c2319e1
Revises: 61e36a2dc20a
Create Date: 2019-08-23 08:15:06.102328

"""

# revision identifiers, used by Alembic.
revision = '64c98c2319e1'
down_revision = '61e36a2dc20a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_load_balancers', sa.Column('host_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_load_balancers', 'host_name')
    # ### end Alembic commands ###