"""empty message

Revision ID: 66b9b2c4c99b
Revises: da7013ac5385
Create Date: 2020-04-24 04:32:48.521922

"""

# revision identifiers, used by Alembic.
revision = '66b9b2c4c99b'
down_revision = 'da7013ac5385'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gcp_tasks', sa.Column('_status', sa.String(length=32), nullable=False))
    op.add_column('gcp_tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('gcp_tasks', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    op.drop_column('gcp_tasks', 'status')
    op.add_column('ibm_tasks', sa.Column('_status', sa.String(length=32), nullable=False))
    op.add_column('ibm_tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('ibm_tasks', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    op.drop_column('ibm_tasks', 'status')
    op.add_column('migration_tasks', sa.Column('_status', sa.Enum('CREATED', 'SUCCESS', 'FAILED'), nullable=False))
    op.add_column('migration_tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('migration_tasks', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    op.drop_column('migration_tasks', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migration_tasks', sa.Column('status', mysql.ENUM('CREATED', 'SUCCESS', 'FAILED'), nullable=False))
    op.drop_column('migration_tasks', 'last_updated_at')
    op.drop_column('migration_tasks', 'completed_at')
    op.drop_column('migration_tasks', '_status')
    op.add_column('ibm_tasks', sa.Column('status', mysql.VARCHAR(length=32), nullable=False))
    op.drop_column('ibm_tasks', 'last_updated_at')
    op.drop_column('ibm_tasks', 'completed_at')
    op.drop_column('ibm_tasks', '_status')
    op.add_column('gcp_tasks', sa.Column('status', mysql.VARCHAR(length=32), nullable=False))
    op.drop_column('gcp_tasks', 'last_updated_at')
    op.drop_column('gcp_tasks', 'completed_at')
    op.drop_column('gcp_tasks', '_status')
    # ### end Alembic commands ###