"""empty message

Revision ID: 66e6d4c324dc
Revises: cad7f120684a
Create Date: 2020-03-09 20:50:32.392854

"""

# revision identifiers, used by Alembic.
revision = '66e6d4c324dc'
down_revision = 'cad7f120684a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_tasks', sa.Column('report', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_tasks', 'report')
    # ### end Alembic commands ###