"""empty message

Revision ID: 69ddb155c068
Revises: 9b75bfb3c7c3
Create Date: 2020-02-06 11:12:19.123684

"""

# revision identifiers, used by Alembic.
revision = '69ddb155c068'
down_revision = '9b75bfb3c7c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_instances', sa.Column('region', sa.String(length=255), nullable=True))
    op.add_column('ibm_public_gateways', sa.Column('region', sa.String(length=255), nullable=True))
    op.add_column('ibm_security_groups', sa.Column('region', sa.String(length=50), nullable=True))
    op.add_column('ibm_subnets', sa.Column('region', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_subnets', 'region')
    op.drop_column('ibm_security_groups', 'region')
    op.drop_column('ibm_public_gateways', 'region')
    op.drop_column('ibm_instances', 'region')
    # ### end Alembic commands ###