"""empty message

Revision ID: 6a5f3a18d51c
Revises: 7c612437389f
Create Date: 2020-04-09 18:10:20.558182

"""

# revision identifiers, used by Alembic.
revision = '6a5f3a18d51c'
down_revision = '7c612437389f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_vpc_networks', sa.Column('crn', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_vpc_networks', 'crn')
    # ### end Alembic commands ###