"""empty message

Revision ID: 6d5233e733fa
Revises: fa690c8fb4e3
Create Date: 2020-01-13 11:27:33.144485

"""

# revision identifiers, used by Alembic.
revision = '6d5233e733fa'
down_revision = 'fa690c8fb4e3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_network_interfaces', 'is_primary',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_network_interfaces', 'is_primary',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###