"""empty message

Revision ID: 71c7d1155e05
Revises: b4ea8afe4805
Create Date: 2020-10-02 10:42:16.450675

"""

# revision identifiers, used by Alembic.
revision = '71c7d1155e05'
down_revision = 'b4ea8afe4805'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_resources', sa.Column('cloud_id', sa.String(length=32), nullable=True))
    op.add_column('billing_resources', sa.Column('cloud_name', sa.String(length=256), nullable=True))
    op.add_column('billing_resources', sa.Column('cloud_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_resources', 'cloud_type')
    op.drop_column('billing_resources', 'cloud_name')
    op.drop_column('billing_resources', 'cloud_id')
    # ### end Alembic commands ###