"""empty message

Revision ID: 758a47d36920
Revises: 066047793788
Create Date: 2021-06-15 00:08:24.164184

"""

# revision identifiers, used by Alembic.
revision = '758a47d36920'
down_revision = '066047793788'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cm_models',
    sa.Column('softlayer_vsi_id', sa.Integer(), nullable=True),
    sa.Column('cm_meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('softlayer_vsi_id')
    )
    op.add_column('ibm_instances_tasks', sa.Column('nas_mig_user_data_script', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_instances_tasks', 'nas_mig_user_data_script')
    op.drop_table('cm_models')
    # ### end Alembic commands ###
