"""empty message

Revision ID: 7690148db552
Revises: 71c7d1155e05
Create Date: 2020-10-20 03:05:15.476808

"""

# revision identifiers, used by Alembic.
revision = '7690148db552'
down_revision = '71c7d1155e05'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_instances', sa.Column('auto_scale_group', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_instances', 'auto_scale_group')
    # ### end Alembic commands ###
