"""empty message

Revision ID: 791a7a43ea6a
Revises: 3556c696852f
Create Date: 2020-02-17 07:52:54.717534

"""

# revision identifiers, used by Alembic.
revision = '791a7a43ea6a'
down_revision = '3556c696852f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ibm_volumes_ibfk_2', 'ibm_volumes', type_='foreignkey')
    op.create_foreign_key('ibm_vol_attachment_vol_ibfk_xi', 'ibm_volumes', 'ibm_volume_attachments', ['volume_attachment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ibm_vol_attachment_vol_ibfk_xi', 'ibm_volumes', type_='foreignkey')
    op.create_foreign_key('ibm_volumes_ibfk_2', 'ibm_volumes', 'ibm_volume_attachments', ['volume_attachment_id'], ['id'])
    # ### end Alembic commands ###
