"""empty message

Revision ID: 7a1688146c45
Revises: 5888f5b26636
Create Date: 2021-10-18 07:02:28.297967

"""

# revision identifiers, used by Alembic.
revision = '7a1688146c45'
down_revision = '5888f5b26636'


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

new_type = sa.Enum("BALANCED", "COMPUTE", "MEMORY", "GPU", "HIGH-MEMORY", "VERY-HIGH-MEMORY", "GPU-V100", name='family')
old_type = sa.Enum("BALANCED", "COMPUTE", "MEMORY", "GPU", "HIGH-MEMORY", "VERY-HIGH-MEMORY", name='family')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instance_profiles', u'family', type_=new_type,
                    existing_type=old_type)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instance_profiles', u'family', type_=old_type,
                    existing_type=new_type)
    # ### end Alembic commands ###
