"""empty message

Revision ID: 7c612437389f
Revises: f676210d72f7
Create Date: 2020-04-05 22:20:47.091855

"""

# revision identifiers, used by Alembic.
revision = '7c612437389f'
down_revision = 'f676210d72f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_load_balancers', sa.Column('base_task_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_load_balancers', 'base_task_id')
    # ### end Alembic commands ###