"""empty message

Revision ID: 7db6ab491f70
Revises: 1df974311bb
Create Date: 2019-10-23 15:31:47.518174

"""

# revision identifiers, used by Alembic.
revision = '7db6ab491f70'
down_revision = '1df974311bb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_vpc_routes', 'href')
    op.add_column('users', sa.Column('data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'data')
    op.add_column('ibm_vpc_routes', sa.Column('href', mysql.VARCHAR(length=300), nullable=True))
    # ### end Alembic commands ###