"""empty message

Revision ID: 7ec873924583
Revises: 64c98c2319e1
Create Date: 2019-08-22 09:06:22.060280

"""

# revision identifiers, used by Alembic.
revision = '7ec873924583'
down_revision = '64c98c2319e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_ike_policy',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ike_version', sa.Integer(), nullable=True),
    sa.Column('key_lifetime', sa.Integer(), nullable=True),
    sa.Column('authentication_algorithm', sa.Enum('md5', 'sha1', 'sha256'), nullable=True),
    sa.Column('encryption_algorithm', sa.Enum('3des', 'aes128', 'aes256'), nullable=True),
    sa.Column('dh_group', sa.Integer(), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=True),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_ipsec_policy',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('authentication_algorithm', sa.Enum('md5', 'sha1', 'sha256'), nullable=False),
    sa.Column('encryption_algorithm', sa.Enum('3des', 'aes128', 'aes256'), nullable=False),
    sa.Column('pfs_dh_group', sa.Enum('group_2', 'group_5', 'group_14', 'disabled'), nullable=False),
    sa.Column('key_lifetime', sa.Integer(), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=True),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_vpn_gateways',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('public_ip', sa.String(length=16), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('gateway_status', sa.String(length=100), nullable=True),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.Column('subnet_id', sa.String(length=32), nullable=True),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['subnet_id'], ['ibm_subnets.id'], ),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_vpn_connections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('local_address', sa.String(length=255), nullable=True),
    sa.Column('peer_address', sa.String(length=255), nullable=False),
    sa.Column('pre_shared_key', sa.String(length=255), nullable=False),
    sa.Column('local_cidrs', sa.Text(), nullable=False),
    sa.Column('peer_cidrs', sa.Text(), nullable=False),
    sa.Column('dpd_action', sa.Enum('restart', 'clear', 'hold', 'none'), nullable=False),
    sa.Column('dpd_interval', sa.Integer(), nullable=False),
    sa.Column('dpd_timeout', sa.Integer(), nullable=False),
    sa.Column('admin_state_up', sa.Boolean(), nullable=False),
    sa.Column('authentication_mode', sa.String(length=100), nullable=False),
    sa.Column('vpn_status', sa.String(length=10), nullable=False),
    sa.Column('route_mode', sa.String(length=100), nullable=True),
    sa.Column('ike_policy_id', sa.String(length=32), nullable=True),
    sa.Column('ipsec_policy_id', sa.String(length=32), nullable=True),
    sa.Column('vpn_gateway_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['ike_policy_id'], ['ibm_ike_policy.id'], ),
    sa.ForeignKeyConstraint(['ipsec_policy_id'], ['ibm_ipsec_policy.id'], ),
    sa.ForeignKeyConstraint(['vpn_gateway_id'], ['ibm_vpn_gateways.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_vpn_connections')
    op.drop_table('ibm_vpn_gateways')
    op.drop_table('ibm_ipsec_policy')
    op.drop_table('ibm_ike_policy')
    # ### end Alembic commands ###
