"""empty message

Revision ID: 7f64fd218db6
Revises: 2025f2a3513a
Create Date: 2020-03-24 11:10:02.756345

"""

# revision identifiers, used by Alembic.
revision = '7f64fd218db6'
down_revision = '2025f2a3513a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed_at_by_admin', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'confirmed_at_by_admin')
    # ### end Alembic commands ###