"""empty message

Revision ID: 831de097401b
Revises: 5d7cf84af732
Create Date: 2021-09-09 14:49:58.781686

"""

# revision identifiers, used by Alembic.
revision = '831de097401b'
down_revision = '5d7cf84af732'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


new_type = sa.Enum("BALANCED", "COMPUTE", "MEMORY", "GPU", "HIGH-MEMORY", "VERY-HIGH-MEMORY", name='family')
old_type = sa.Enum("BALANCED", "COMPUTE", "MEMORY", "GPU", "HIGH-MEMORY", name='family')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instance_profiles', u'family', type_=new_type,
                    existing_type=old_type)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instance_profiles', u'family', type_=old_type,
                    existing_type=new_type)
    # ### end Alembic commands ###

