"""empty message

Revision ID: 8674a848e57d
Revises: 5c581f12d900
Create Date: 2021-08-13 18:27:55.321061

"""

# revision identifiers, used by Alembic.
revision = '8674a848e57d'
down_revision = '5c581f12d900'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    op.drop_table('ibm_tokens')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('expire_at', mysql.DATETIME(), nullable=False),
    sa.Column('attempts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('token_type', mysql.ENUM('PIN', 'ACCESS', 'REFRESH'), nullable=False),
    sa.Column('is_black_listed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('data', mysql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ibm_tokens',
    sa.Column('id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ibm_tokens_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('devices',
    sa.Column('id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('finger_print', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('registered_at', mysql.DATETIME(), nullable=False),
    sa.Column('device_info', mysql.JSON(), nullable=False),
    sa.Column('session_token', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('status', mysql.ENUM('trusted', 'untrusted'), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='devices_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###