"""empty message

Revision ID: 8adb390b00ec
Revises: 151634748d1e
Create Date: 2019-08-05 07:46:03.449586

"""

# revision identifiers, used by Alembic.
revision = '8adb390b00ec'
down_revision = '151634748d1e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_images', sa.Column('os_vendor', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_images', 'os_vendor')
    # ### end Alembic commands ###