"""empty message

Revision ID: 91da72c279f9
Revises: be6a515e534b
Create Date: 2020-06-02 07:14:17.572957

"""

# revision identifiers, used by Alembic.
revision = '91da72c279f9'
down_revision = 'be6a515e534b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_resources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=True),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_data', sa.JSON(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_resources')
    # ### end Alembic commands ###
