"""empty message

Revision ID: 924b390d19e6
Revises: 989005c1356b
Create Date: 2019-10-03 11:22:27.393850

"""

# revision identifiers, used by Alembic.
revision = '924b390d19e6'
down_revision = '989005c1356b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_network_interfaces_security_groups',
    sa.Column('network_interface_id', sa.String(length=32), nullable=False),
    sa.Column('security_group_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['network_interface_id'], ['ibm_network_interfaces.id'], ),
    sa.ForeignKeyConstraint(['security_group_id'], ['ibm_security_groups.id'], ),
    sa.PrimaryKeyConstraint('network_interface_id', 'security_group_id')
    )
    op.drop_constraint('ibm_network_interfaces_ibfk_2', 'ibm_network_interfaces', type_='foreignkey')
    op.drop_column('ibm_network_interfaces', 'security_group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_network_interfaces', sa.Column('security_group_id', mysql.VARCHAR(length=32), nullable=False))
    op.create_foreign_key('ibm_network_interfaces_ibfk_2', 'ibm_network_interfaces', 'ibm_security_groups', ['security_group_id'], ['id'])
    op.drop_table('ibm_network_interfaces_security_groups')
    # ### end Alembic commands ###
