"""empty message

Revision ID: 9862a399a35c
Revises: bc14742ba88a
Create Date: 2020-04-29 19:47:50.227185

"""

# revision identifiers, used by Alembic.
revision = '9862a399a35c'
down_revision = 'bc14742ba88a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_tasks',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('cloud_type', sa.String(length=32), nullable=False),
    sa.Column('_status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('ibm_instances', 'cos_bucket_name')
    op.drop_column('ibm_instances', 'is_image_migration')
    op.add_column('ibm_instances_tasks', sa.Column('bucket_name', sa.String(length=255), nullable=True))
    op.add_column('ibm_instances_tasks', sa.Column('bucket_object', sa.String(length=255), nullable=True))
    op.add_column('ibm_instances_tasks', sa.Column('classical_account_id', sa.String(length=32), nullable=True))
    op.add_column('ibm_instances_tasks', sa.Column('classical_image_id', sa.String(length=32), nullable=True))
    op.add_column('ibm_instances_tasks', sa.Column('classical_image_name', sa.String(length=255), nullable=True))
    op.add_column('ibm_instances_tasks', sa.Column('cloud_id', sa.String(length=32), nullable=False))
    op.add_column('ibm_instances_tasks', sa.Column('custom_image', sa.String(length=255), nullable=True))
    op.add_column('ibm_instances_tasks', sa.Column('image_conversion_task_id', sa.String(length=32), nullable=True))
    op.add_column('ibm_instances_tasks', sa.Column('image_location', sa.Enum('classical_vsi', 'classical_image', 'cos_vhd', 'cos_qcow2', 'custom_image', 'public_image'), nullable=False))
    op.add_column('ibm_instances_tasks', sa.Column('image_type', sa.Integer(), nullable=True))
    op.add_column('ibm_instances_tasks', sa.Column('public_image', sa.String(length=255), nullable=True))
    op.add_column('ibm_instances_tasks', sa.Column('task_type', sa.Enum('take_snapshot', 'upload_to_cos', 'image_conversion', 'create_custom_image', 'create_instance_subsequent'), nullable=False))
    op.add_column('ibm_instances_tasks', sa.Column('vpc_image_name', sa.String(length=255), nullable=True))
    op.drop_constraint('ibm_instances_tasks_ibfk_1', 'ibm_instances_tasks', type_='foreignkey')
    op.create_foreign_key('ibm_instances_tasks_ibfk_12', 'ibm_instances_tasks', 'ibm_clouds', ['cloud_id'], ['id'])
    op.drop_column('ibm_instances_tasks', 'softlayer_cloud_id')
    op.drop_column('ibm_instances_tasks', 'ic_task_id')
    op.drop_column('ibm_instances_tasks', 'type')
    op.drop_column('ibm_instances_tasks', 'cloud')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_instances_tasks', sa.Column('cloud', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('ibm_instances_tasks', sa.Column('type', mysql.ENUM('take_snapshot', 'upload_to_cos', 'image_conversion', 'create_custom_image', 'create_instance_subsequent'), nullable=False))
    op.add_column('ibm_instances_tasks', sa.Column('ic_task_id', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('ibm_instances_tasks', sa.Column('softlayer_cloud_id', mysql.VARCHAR(length=32), nullable=True))
    op.drop_constraint('ibm_instances_tasks_ibfk_12', 'ibm_instances_tasks', type_='foreignkey')
    op.create_foreign_key('ibm_instances_tasks_ibfk_1', 'ibm_instances_tasks', 'ibm_clouds', ['cloud'], ['id'])
    op.drop_column('ibm_instances_tasks', 'vpc_image_name')
    op.drop_column('ibm_instances_tasks', 'task_type')
    op.drop_column('ibm_instances_tasks', 'public_image')
    op.drop_column('ibm_instances_tasks', 'image_type')
    op.drop_column('ibm_instances_tasks', 'image_location')
    op.drop_column('ibm_instances_tasks', 'image_conversion_task_id')
    op.drop_column('ibm_instances_tasks', 'custom_image')
    op.drop_column('ibm_instances_tasks', 'cloud_id')
    op.drop_column('ibm_instances_tasks', 'classical_image_name')
    op.drop_column('ibm_instances_tasks', 'classical_image_id')
    op.drop_column('ibm_instances_tasks', 'classical_account_id')
    op.drop_column('ibm_instances_tasks', 'bucket_object')
    op.drop_column('ibm_instances_tasks', 'bucket_name')
    op.add_column('ibm_instances', sa.Column('is_image_migration', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('ibm_instances', sa.Column('cos_bucket_name', mysql.VARCHAR(length=500), nullable=True))
    op.drop_table('sync_tasks')
    # ### end Alembic commands ###
