"""empty message

Revision ID: 989005c1356b
Revises: cbf2d1a5cd37
Create Date: 2019-10-10 08:26:52.222036

"""

# revision identifiers, used by Alembic.
revision = '989005c1356b'
down_revision = 'cbf2d1a5cd37'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'type')
    op.add_column('templates', sa.Column('type', sa.Enum('PRE_DEFINED', 'USER_MANAGED'), nullable=False), )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'type')
    op.add_column('templates', sa.Column('type', sa.Enum('PRE_BUILT', 'USER_MANAGED'), nullable=False), )
    # ### end Alembic commands ###
