"""empty message

Revision ID: 9b75bfb3c7c3
Revises: cb0204908db0
Create Date: 2020-01-23 07:24:57.827912

"""

# revision identifiers, used by Alembic.
revision = '9b75bfb3c7c3'
down_revision = 'cb0204908db0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_instances', sa.Column('instance_status', sa.String(length=50), nullable=True))
    op.add_column('ibm_load_balancers', sa.Column('provisioning_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_load_balancers', 'provisioning_status')
    op.drop_column('ibm_instances', 'instance_status')
    # ### end Alembic commands ###