"""empty message

Revision ID: a08aa65c7816
Revises: dd95e3ec614a
Create Date: 2019-12-03 10:59:56.666515

"""

# revision identifiers, used by Alembic.
revision = 'a08aa65c7816'
down_revision = 'dd95e3ec614a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instances', 'image_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instances', 'image_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###