"""empty message

Revision ID: a0fa679811dd
Revises: 6d5233e733fa
Create Date: 2020-01-14 13:29:21.758553

"""

# revision identifiers, used by Alembic.
revision = 'a0fa679811dd'
down_revision = '6d5233e733fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_ibm_floating_ip_name_cloud_id', 'ibm_floating_ips', type_='unique')
    op.create_unique_constraint('uix_ibm_floating_ip_name_cloud_id', 'ibm_floating_ips', ['name', 'region', 'cloud_id'])
    op.drop_constraint('uix_ibm_ike_policy_name_cloud_id', 'ibm_ike_policy', type_='unique')
    op.create_unique_constraint('uix_ibm_ike_policy_name_cloud_id', 'ibm_ike_policy', ['name', 'region', 'cloud_id'])
    op.drop_constraint('uix_ibm_image_name_visibility_cloud_id', 'ibm_images', type_='unique')
    op.create_unique_constraint('uix_ibm_image_name_visibility_cloud_id', 'ibm_images', ['name', 'cloud_id', 'region', 'visibility'])
    op.drop_constraint('uix_ibm_ipsec_policy_name_cloud_id', 'ibm_ipsec_policy', type_='unique')
    op.create_unique_constraint('uix_ibm_ipsec_policy_name_cloud_id', 'ibm_ipsec_policy', ['name', 'region', 'cloud_id'])
    op.drop_constraint('uix_ibm_volume_name_instance_id', 'ibm_volume_attachments', type_='unique')
    op.create_unique_constraint('uix_ibm_volume_name_instance_id', 'ibm_volume_attachments', ['name', 'resource_id', 'instance_id'])
    op.add_column('ibm_volumes', sa.Column('region', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_volumes', 'region')
    op.drop_constraint('uix_ibm_volume_name_instance_id', 'ibm_volume_attachments', type_='unique')
    op.create_unique_constraint('uix_ibm_volume_name_instance_id', 'ibm_volume_attachments', ['name', 'instance_id'])
    op.drop_constraint('uix_ibm_ipsec_policy_name_cloud_id', 'ibm_ipsec_policy', type_='unique')
    op.create_unique_constraint('uix_ibm_ipsec_policy_name_cloud_id', 'ibm_ipsec_policy', ['name', 'cloud_id'])
    op.drop_constraint('uix_ibm_image_name_visibility_cloud_id', 'ibm_images', type_='unique')
    op.create_unique_constraint('uix_ibm_image_name_visibility_cloud_id', 'ibm_images', ['name', 'cloud_id', 'visibility'])
    op.drop_constraint('uix_ibm_ike_policy_name_cloud_id', 'ibm_ike_policy', type_='unique')
    op.create_unique_constraint('uix_ibm_ike_policy_name_cloud_id', 'ibm_ike_policy', ['name', 'cloud_id'])
    op.drop_constraint('uix_ibm_floating_ip_name_cloud_id', 'ibm_floating_ips', type_='unique')
    op.create_unique_constraint('uix_ibm_floating_ip_name_cloud_id', 'ibm_floating_ips', ['name', 'cloud_id'])
    # ### end Alembic commands ###
