"""empty message

Revision ID: a6616e7bf93a
Revises: e347ec8bfc75
Create Date: 2020-06-10 11:05:00.298874

"""

# revision identifiers, used by Alembic.
revision = 'a6616e7bf93a'
down_revision = 'e347ec8bfc75'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('token_type', sa.Enum('PIN', 'ACCESS', 'REFRESH'), nullable=False),
    sa.Column('is_black_listed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###