"""empty message

Revision ID: af3f97a71cb8
Revises: 1ea6dae600a2
Create Date: 2020-05-29 08:26:36.257419

"""

# revision identifiers, used by Alembic.
revision = 'af3f97a71cb8'
down_revision = '1ea6dae600a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_instances', sa.Column('data_center', sa.String(length=255), nullable=False))
    op.add_column('ibm_instances', sa.Column('instance_type', sa.Enum('PUBLIC', 'PRIVATE', 'DEDICATED'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_instances', 'instance_type')
    op.drop_column('ibm_instances', 'data_center')
    # ### end Alembic commands ###