"""empty message

Revision ID: b07aaf6cbd43
Revises: 6a5f3a18d51c
Create Date: 2020-04-16 18:27:58.792016

"""

# revision identifiers, used by Alembic.
revision = 'b07aaf6cbd43'
down_revision = 'b8a6450efd1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transit_gateways',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('crn', sa.String(length=255), nullable=True),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.Column('is_global_route', sa.Boolean(), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('IBM'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('gateway_status', sa.Enum('available', 'failed', 'pending', 'deleting'), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transit_gateway_connections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('connection_status', sa.Enum('attached', 'failed', 'pending', 'deleting'), nullable=True),
    sa.Column('network_type', sa.Enum('vpc', 'classic'), nullable=False),
    sa.Column('network_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('vpc_id', sa.String(length=32), nullable=True),
    sa.Column('transit_gateway_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['transit_gateway_id'], ['transit_gateways.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'transit_gateway_id', name='uix_transit_connection_name_transit_gateway_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transit_gateway_connections')
    op.drop_table('transit_gateways')
    # ### end Alembic commands ###