"""empty message

Revision ID: b52331519258
Revises: 69ddb155c068
Create Date: 2020-02-09 09:09:48.366096

"""

# revision identifiers, used by Alembic.
revision = 'b52331519258'
down_revision = '69ddb155c068'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_ibm_name_vpc_id_cloud_id_region', 'ibm_instances', ['name', 'vpc_id', 'cloud_id', 'region'])
    op.drop_index('uix_ibm_name_vpc_id_cloud_id', table_name='ibm_instances')
    op.create_unique_constraint('uix_ibm_lb_name_vpc_cloud_id_region', 'ibm_load_balancers', ['name', 'vpc_id', 'cloud_id', 'region'])
    op.drop_index('uix_ibm_lb_name_vpc_cloud_id', table_name='ibm_load_balancers')
    op.drop_constraint('uix_ibm_public_gateway_name_vpc_cloud_id', 'ibm_public_gateways', type_='unique')
    op.create_unique_constraint('uix_ibm_public_gateway_name_vpc_cloud_id', 'ibm_public_gateways', ['name', 'vpc_id', 'cloud_id', 'region'])
    op.create_unique_constraint('uix_ibm_security_group_name_vpc_id_region', 'ibm_security_groups', ['name', 'vpc_id', 'region'])
    op.drop_index('uix_ibm_security_group_name_vpc_id', table_name='ibm_security_groups')
    op.drop_constraint('uix_ibm_subnet_name_cloud_id_vpc_id', 'ibm_subnets', type_='unique')
    op.create_unique_constraint('uix_ibm_subnet_name_cloud_id_vpc_id', 'ibm_subnets', ['name', 'cloud_id', 'vpc_id', 'region'])
    op.create_unique_constraint('uix_ibm_vpc_network_name_cloud_id_region', 'ibm_vpc_networks', ['name', 'cloud_id', 'region'])
    op.drop_index('uix_ibm_vpc_network_name_cloud_id', table_name='ibm_vpc_networks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uix_ibm_vpc_network_name_cloud_id', 'ibm_vpc_networks', ['name', 'cloud_id'], unique=True)
    op.drop_constraint('uix_ibm_vpc_network_name_cloud_id_region', 'ibm_vpc_networks', type_='unique')
    op.drop_constraint('uix_ibm_subnet_name_cloud_id_vpc_id', 'ibm_subnets', type_='unique')
    op.create_unique_constraint('uix_ibm_subnet_name_cloud_id_vpc_id', 'ibm_subnets', ['name', 'cloud_id', 'vpc_id'])
    op.create_index('uix_ibm_security_group_name_vpc_id', 'ibm_security_groups', ['name', 'vpc_id'], unique=True)
    op.drop_constraint('uix_ibm_security_group_name_vpc_id_region', 'ibm_security_groups', type_='unique')
    op.drop_constraint('uix_ibm_public_gateway_name_vpc_cloud_id', 'ibm_public_gateways', type_='unique')
    op.create_unique_constraint('uix_ibm_public_gateway_name_vpc_cloud_id', 'ibm_public_gateways', ['name', 'vpc_id', 'cloud_id'])
    op.create_index('uix_ibm_lb_name_vpc_cloud_id', 'ibm_load_balancers', ['name', 'vpc_id', 'cloud_id'], unique=True)
    op.drop_constraint('uix_ibm_lb_name_vpc_cloud_id_region', 'ibm_load_balancers', type_='unique')
    op.create_index('uix_ibm_name_vpc_id_cloud_id', 'ibm_instances', ['name', 'vpc_id', 'cloud_id'], unique=True)
    op.drop_constraint('uix_ibm_name_vpc_id_cloud_id_region', 'ibm_instances', type_='unique')
    # ### end Alembic commands ###