"""empty message

Revision ID: b820cabaaa21
Revises: 7ec873924583
Create Date: 2019-08-28 07:25:14.090629

"""

# revision identifiers, used by Alembic.
revision = 'b820cabaaa21'
down_revision = '7ec873924583'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_pool_members', sa.Column('resource_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_pool_members', 'resource_id')
    # ### end Alembic commands ###