"""empty message

Revision ID: b8a6450efd1b
Revises: cdcfef397d1b
Create Date: 2020-04-18 18:26:00.810414

"""

# revision identifiers, used by Alembic.
revision = 'b8a6450efd1b'
down_revision = 'cdcfef397d1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_sub_tasks', sa.Column('status', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_sub_tasks', 'status')
    # ### end Alembic commands ###