"""empty message

Revision ID: ba15fb085111
Revises: c039a01956fb
Create Date: 2019-05-02 06:27:37.638884

"""

# revision identifiers, used by Alembic.
revision = 'ba15fb085111'
down_revision = 'c039a01956fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gcp_addresses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('ip_version', sa.String(length=255), nullable=True),
    sa.Column('cloud_project_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_project_id'], ['gcp_cloud_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gcp_addresses')
    # ### end Alembic commands ###