"""empty message

Revision ID: be6a515e534b
Revises: af3f97a71cb8
Create Date: 2020-05-30 14:24:54.743453

"""

# revision identifiers, used by Alembic.
revision = 'be6a515e534b'
down_revision = 'af3f97a71cb8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instances', 'data_center',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ibm_instances', 'data_center',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    # ### end Alembic commands ###