"""empty message

Revision ID: bf14e9db09cf
Revises: 48ced95698ad
Create Date: 2020-01-12 17:14:53.412457

"""

# revision identifiers, used by Alembic.
revision = 'bf14e9db09cf'
down_revision = '48ced95698ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_instances', sa.Column('state', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_instances', 'state')
    # ### end Alembic commands ###
