"""empty message

Revision ID: bf1530701913
Revises: 344bec98dcb2
Create Date: 2019-06-18 07:47:25.832937

"""

# revision identifiers, used by Alembic.
revision = 'bf1530701913'
down_revision = '344bec98dcb2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gcp_firewall_tags',
    sa.Column('tag_id', sa.String(length=32), nullable=False),
    sa.Column('firewall_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['firewall_id'], ['gcp_firewall_rules.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['gcp_tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'firewall_id')
    )
    op.create_table('gcp_firewall_target_tags',
    sa.Column('tag_id', sa.String(length=32), nullable=False),
    sa.Column('firewall_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['firewall_id'], ['gcp_firewall_rules.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['gcp_tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'firewall_id')
    )
    op.drop_column('gcp_firewall_rules', 'target_tags')
    op.drop_column('gcp_firewall_rules', 'tags')
    op.add_column('gcp_network_interfaces', sa.Column('address_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('gcp_network_itf_ibfk_1', 'gcp_network_interfaces', 'gcp_addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gcp_network_itf_ibfk_1', 'gcp_network_interfaces', type_='foreignkey')
    op.drop_column('gcp_network_interfaces', 'address_id')
    op.add_column('gcp_firewall_rules', sa.Column('tags', mysql.TEXT(), nullable=True))
    op.add_column('gcp_firewall_rules', sa.Column('target_tags', mysql.TEXT(), nullable=True))
    op.drop_table('gcp_firewall_target_tags')
    op.drop_table('gcp_firewall_tags')
    # ### end Alembic commands ###