"""empty message

Revision ID: c039a01956fb
Revises: 19d2ee37e932
Create Date: 2019-04-18 10:41:04.169242

"""

# revision identifiers, used by Alembic.
revision = 'c039a01956fb'
down_revision = '19d2ee37e932'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gcp_subnets', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('gcp_vpc_networks', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gcp_vpc_networks', 'status')
    op.drop_column('gcp_subnets', 'status')
    # ### end Alembic commands ###