"""empty message

Revision ID: c04ee08449fd
Revises: 300eaae04155
Create Date: 2020-01-16 13:53:09.905013

"""

# revision identifiers, used by Alembic.
revision = 'c04ee08449fd'
down_revision = '300eaae04155'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_network_acls', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.add_column('ibm_network_acls', sa.Column('vpc_id', sa.String(length=32), nullable=True))
    op.create_unique_constraint('uix_ibm_acl_name_vpc_region_cloud_id', 'ibm_network_acls', ['name', 'region', 'vpc_id', 'cloud_id'])
    op.drop_index('uix_ibm_acl_name_region_cloud_id', table_name='ibm_network_acls')
    op.create_foreign_key('acl_vpc_ibfk_4', 'ibm_network_acls', 'ibm_vpc_networks', ['vpc_id'], ['id'])
    op.drop_constraint('ibm_vpc_networks_ibfk_2', 'ibm_vpc_networks', type_='foreignkey')
    op.drop_column('ibm_vpc_networks', 'network_acl_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_vpc_networks', sa.Column('network_acl_id', mysql.VARCHAR(length=32), nullable=True))
    op.create_foreign_key('ibm_vpc_networks_ibfk_2', 'ibm_vpc_networks', 'ibm_network_acls', ['network_acl_id'], ['id'])
    op.drop_constraint('acl_vpc_ibfk_4', 'ibm_network_acls', type_='foreignkey')
    op.create_index('uix_ibm_acl_name_region_cloud_id', 'ibm_network_acls', ['name', 'region', 'cloud_id'], unique=True)
    op.drop_constraint('uix_ibm_acl_name_vpc_region_cloud_id', 'ibm_network_acls', type_='unique')
    op.drop_column('ibm_network_acls', 'vpc_id')
    op.drop_column('ibm_network_acls', 'is_default')
    # ### end Alembic commands ###