"""empty message

Revision ID: c4addc02d3b2
Revises: 42eadc2ecc39
Create Date: 2020-12-28 11:31:41.456377

"""

# revision identifiers, used by Alembic.
revision = 'c4addc02d3b2'
down_revision = '42eadc2ecc39'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_floating_ips', sa.Column('resource_group_id', sa.String(length=32), nullable=True))
    op.create_foreign_key("fk_resource_grp_floating_ip", 'ibm_floating_ips', 'ibm_resource_groups', ['resource_group_id'], ['id'])
    op.add_column('ibm_network_acls', sa.Column('resource_group_id', sa.String(length=32), nullable=True))
    op.create_foreign_key("fk_resource_grp_acl", 'ibm_network_acls', 'ibm_resource_groups', ['resource_group_id'], ['id'])
    op.add_column('ibm_public_gateways', sa.Column('resource_group_id', sa.String(length=32), nullable=True))
    op.create_foreign_key("fk_resource_grp_pub_gateway", 'ibm_public_gateways', 'ibm_resource_groups', ['resource_group_id'], ['id'])
    op.add_column('ibm_subnets', sa.Column('resource_group_id', sa.String(length=32), nullable=True))
    op.create_foreign_key("fk_resource_grp_subnets", 'ibm_subnets', 'ibm_resource_groups', ['resource_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_resource_grp_subnets", 'ibm_subnets', type_='foreignkey')
    op.drop_column('ibm_subnets', 'resource_group_id')
    op.drop_constraint("fk_resource_grp_pub_gateway", 'ibm_public_gateways', type_='foreignkey')
    op.drop_column('ibm_public_gateways', 'resource_group_id')
    op.drop_constraint("fk_resource_grp_acl", 'ibm_network_acls', type_='foreignkey')
    op.drop_column('ibm_network_acls', 'resource_group_id')
    op.drop_constraint("fk_resource_grp_floating_ip", 'ibm_floating_ips', type_='foreignkey')
    op.drop_column('ibm_floating_ips', 'resource_group_id')
    # ### end Alembic commands ###
