"""empty message

Revision ID: c659df275c1c
Revises: f068e2c43cc9
Create Date: 2020-07-22 07:31:08.639175

"""

# revision identifiers, used by Alembic.
revision = 'c659df275c1c'
down_revision = 'f068e2c43cc9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_images', sa.Column('vpc_image_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_images', 'vpc_image_name')
    # ### end Alembic commands ###

