"""empty message

Revision ID: c99fe9371952
Revises: 758a47d36920
Create Date: 2021-06-22 14:45:29.309329

"""

# revision identifiers, used by Alembic.
revision = 'c99fe9371952'
down_revision = '758a47d36920'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_dedicated_host_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('href', sa.Text(), nullable=True),
    sa.Column('family', sa.Enum('balanced', 'memory', 'compute'), nullable=True),
    sa.Column('class', sa.String(length=20), nullable=True),
    sa.Column('socket_count', sa.JSON(), nullable=True),
    sa.Column('memory', sa.JSON(), nullable=True),
    sa.Column('vcpu_architecture', sa.JSON(), nullable=True),
    sa.Column('vcpu_count', sa.JSON(), nullable=True),
    sa.Column('disks', sa.JSON(), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_dedicated_host_groups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('crn', sa.Text(), nullable=True),
    sa.Column('href', sa.Text(), nullable=True),
    sa.Column('family', sa.Enum('balanced', 'memory', 'compute'), nullable=True),
    sa.Column('class', sa.String(length=128), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_dh_profile_supported_instance_profiles',
    sa.Column('dh_profile_id', sa.String(length=32), nullable=False),
    sa.Column('instance_profile_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dh_profile_id'], ['ibm_dedicated_host_profiles.id'], ),
    sa.ForeignKeyConstraint(['instance_profile_id'], ['ibm_instance_profiles.id'], ),
    sa.PrimaryKeyConstraint('dh_profile_id', 'instance_profile_id')
    )
    op.create_table('ibm_dedicated_hosts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('crn', sa.Text(), nullable=True),
    sa.Column('href', sa.Text(), nullable=True),
    sa.Column('instance_placement_enabled', sa.Boolean(), nullable=True),
    sa.Column('lifecycle_state', sa.Enum('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting', 'suspended'), nullable=True),
    sa.Column('available_memory', sa.Integer(), nullable=True),
    sa.Column('memory', sa.Integer(), nullable=True),
    sa.Column('provisionable', sa.Boolean(), nullable=True),
    sa.Column('socket_count', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('available', 'degraded', 'migrating', 'unavailable'), nullable=True),
    sa.Column('vcpu', sa.JSON(), nullable=True),
    sa.Column('available_vcpu', sa.JSON(), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.Column('dedicated_host_group_id', sa.String(length=32), nullable=True),
    sa.Column('dedicated_host_profile_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['dedicated_host_group_id'], ['ibm_dedicated_host_groups.id'], ),
    sa.ForeignKeyConstraint(['dedicated_host_profile_id'], ['ibm_dedicated_host_profiles.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_dh_group_supported_instance_profiles',
    sa.Column('dh_group_id', sa.String(length=32), nullable=False),
    sa.Column('instance_profile_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dh_group_id'], ['ibm_dedicated_host_groups.id'], ),
    sa.ForeignKeyConstraint(['instance_profile_id'], ['ibm_instance_profiles.id'], ),
    sa.PrimaryKeyConstraint('dh_group_id', 'instance_profile_id')
    )
    op.create_table('ibm_dedicated_host_disks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('href', sa.Text(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.Column('interface_type', sa.Enum('nvme'), nullable=True),
    sa.Column('provisionable', sa.Boolean(), nullable=True),
    sa.Column('supported_instance_interface_types', sa.JSON(), nullable=True),
    sa.Column('lifecycle_state', sa.Enum('deleting', 'failed', 'pending', 'stable', 'updating', 'waiting', 'suspended'), nullable=True),
    sa.Column('dedicated_host_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['dedicated_host_id'], ['ibm_dedicated_hosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ibm_dh_supported_instance_profiles',
    sa.Column('dh_id', sa.String(length=32), nullable=False),
    sa.Column('instance_profile_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dh_id'], ['ibm_dedicated_hosts.id'], ),
    sa.ForeignKeyConstraint(['instance_profile_id'], ['ibm_instance_profiles.id'], ),
    sa.PrimaryKeyConstraint('dh_id', 'instance_profile_id')
    )
    op.add_column('ibm_instances', sa.Column('dedicated_host_group_id', sa.String(length=32), nullable=True))
    op.add_column('ibm_instances', sa.Column('dedicated_host_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('ibfk_ibm_instances_ibm_dh_groups_1', 'ibm_instances', 'ibm_dedicated_host_groups', ['dedicated_host_group_id'], ['id'])
    op.create_foreign_key('ibfk_ibm_instances_ibm_dhs_1', 'ibm_instances', 'ibm_dedicated_hosts', ['dedicated_host_id'], ['id'])
    op.add_column('ibm_instances_tasks', sa.Column('fe_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_instances_tasks', 'fe_json')
    op.drop_constraint('ibfk_ibm_instances_ibm_dhs_1', 'ibm_instances', type_='foreignkey')
    op.drop_constraint('ibfk_ibm_instances_ibm_dh_groups_1', 'ibm_instances', type_='foreignkey')
    op.drop_column('ibm_instances', 'dedicated_host_id')
    op.drop_column('ibm_instances', 'dedicated_host_group_id')
    op.drop_table('ibm_dh_supported_instance_profiles')
    op.drop_table('ibm_dedicated_host_disks')
    op.drop_table('ibm_dh_group_supported_instance_profiles')
    op.drop_table('ibm_dedicated_hosts')
    op.drop_table('ibm_dh_profile_supported_instance_profiles')
    op.drop_table('ibm_dedicated_host_groups')
    op.drop_table('ibm_dedicated_host_profiles')
    # ### end Alembic commands ###
