"""empty message
Revision ID: ca8fe78bbb8f
Revises: 0bf737b21aad
Create Date: 2021-08-02 12:58:28.991491
"""

# revision identifiers, used by Alembic.
revision = 'ca8fe78bbb8f'
down_revision = '0bf737b21aad'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_dashboard_settings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pin_status', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ibm_dashboard_settings')
    # ### end Alembic commands ###