"""empty message

Revision ID: cad7f120684a
Revises: 0846512ef607
Create Date: 2020-03-06 12:24:41.932734

"""

# revision identifiers, used by Alembic.
revision = 'cad7f120684a'
down_revision = '0846512ef607'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('IBM', 'GCP'), nullable=False),
    sa.Column('request_metadata', sa.Text(), nullable=True),
    sa.Column('softlayer_id', sa.String(length=32), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['softlayer_id'], ['softlayer_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('uix_ibm_address_prefix_name_vpc_id', 'ibm_address_prefixes', ['name', 'vpc_id'])
    op.drop_index('uix_ibm_address_prefix_name_vpc_id_is_provisioning', table_name='ibm_address_prefixes')
    op.drop_column('ibm_address_prefixes', 'is_provisioning')
    op.create_unique_constraint('uix_ibm_ike_policy_name_region_cloud_id', 'ibm_ike_policy', ['name', 'region', 'cloud_id'])
    op.drop_index('uix_ibm_ike_policy_name_region_cloud_id_is_provisioning', table_name='ibm_ike_policy')
    op.drop_column('ibm_ike_policy', 'is_provisioning')
    op.create_unique_constraint('uix_ibm_name_vpc_id_cloud_id_region', 'ibm_instances', ['name', 'vpc_id', 'cloud_id'])
    op.drop_index('uix_ibm_name_vpc_id_cloud_id_region_is_provisioning', table_name='ibm_instances')
    op.drop_column('ibm_instances', 'is_provisioning')
    op.create_unique_constraint('uix_ibm_ipsec_policy_name_region_cloud_id', 'ibm_ipsec_policy', ['name', 'region', 'cloud_id'])
    op.drop_index('uix_ibm_ipsec_policy_name_region_cloud_id_is_provisioning', table_name='ibm_ipsec_policy')
    op.drop_column('ibm_ipsec_policy', 'is_provisioning')
    op.create_unique_constraint('uix_ibm_lb_name_vpc_cloud_id_region', 'ibm_load_balancers', ['name', 'vpc_id', 'cloud_id', 'region'])
    op.drop_index('uix_ibm_lb_name_vpc_cloud_id_region_is_provisioning', table_name='ibm_load_balancers')
    op.drop_column('ibm_load_balancers', 'is_provisioning')
    op.create_unique_constraint('uix_ibm_acl_name_vpc_region_cloud_id', 'ibm_network_acls', ['name', 'region', 'vpc_id', 'cloud_id'])
    op.drop_index('uix_ibm_acl_name_vpc_region_cloud_id_is_provisioning', table_name='ibm_network_acls')
    op.drop_column('ibm_network_acls', 'is_provisioning')
    op.create_unique_constraint('uix_ibm_public_gateway_name_vpc_cloud_id', 'ibm_public_gateways', ['name', 'vpc_id', 'cloud_id', 'region'])
    op.drop_index('uix_ibm_public_gateway_name_vpc_cloud_id_is_provisioning', table_name='ibm_public_gateways')
    op.drop_column('ibm_public_gateways', 'is_provisioning')
    op.create_unique_constraint('uix_ibm_security_group_name_vpc_id_region', 'ibm_security_groups', ['name', 'vpc_id', 'region'])
    op.drop_index('uix_ibm_security_group_name_vpc_id_region_is_provisioning', table_name='ibm_security_groups')
    op.drop_column('ibm_security_groups', 'is_provisioning')
    op.create_unique_constraint('uix_ibm_ssh_name_region_cloud_id', 'ibm_ssh_keys', ['name', 'region', 'cloud_id'])
    op.drop_index('uix_ibm_ssh_name_region_cloud_id_is_provisioning', table_name='ibm_ssh_keys')
    op.drop_column('ibm_ssh_keys', 'is_provisioning')
    op.drop_constraint('uix_ibm_subnet_name_cloud_id_vpc_id', 'ibm_subnets', type_='unique')
    op.create_unique_constraint('uix_ibm_subnet_name_cloud_id_vpc_id', 'ibm_subnets', ['name', 'cloud_id', 'vpc_id', 'region'])
    op.drop_column('ibm_subnets', 'is_provisioning')
    op.add_column('ibm_vpc_networks', sa.Column('workspace_id', sa.String(length=32), nullable=True))
    op.drop_constraint('softlayer_clouds', 'ibm_vpc_networks', type_='foreignkey')
    op.create_foreign_key('sl_ibfk_1', 'ibm_vpc_networks', 'workspaces', ['workspace_id'], ['id'])
    op.drop_column('ibm_vpc_networks', 'softlayer_id')
    op.drop_column('ibm_vpc_networks', 'is_workspace')
    op.create_unique_constraint('uix_ibm_vpn_gateway_vpc_cloud_id', 'ibm_vpn_gateways', ['name', 'vpc_id', 'cloud_id'])
    op.drop_index('uix_ibm_vpn_gateway_vpc_cloud_id_is_provisioning', table_name='ibm_vpn_gateways')
    op.drop_column('ibm_vpn_gateways', 'is_provisioning')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_vpn_gateways', sa.Column('is_provisioning', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('uix_ibm_vpn_gateway_vpc_cloud_id_is_provisioning', 'ibm_vpn_gateways', ['name', 'vpc_id', 'cloud_id', 'is_provisioning'], unique=True)
    op.drop_constraint('uix_ibm_vpn_gateway_vpc_cloud_id', 'ibm_vpn_gateways', type_='unique')
    op.add_column('ibm_vpc_networks', sa.Column('is_workspace', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('ibm_vpc_networks', sa.Column('softlayer_id', mysql.VARCHAR(length=32), nullable=True))
    op.drop_constraint('sl_ibfk_1', 'ibm_vpc_networks', type_='foreignkey')
    op.create_foreign_key('softlayer_clouds', 'ibm_vpc_networks', 'softlayer_clouds', ['softlayer_id'], ['id'])
    op.drop_column('ibm_vpc_networks', 'workspace_id')
    op.add_column('ibm_subnets', sa.Column('is_provisioning', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint('uix_ibm_subnet_name_cloud_id_vpc_id', 'ibm_subnets', type_='unique')
    op.create_unique_constraint('uix_ibm_subnet_name_cloud_id_vpc_id', 'ibm_subnets', ['name', 'cloud_id', 'vpc_id', 'region', 'is_provisioning'])
    op.add_column('ibm_ssh_keys', sa.Column('is_provisioning', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('uix_ibm_ssh_name_region_cloud_id_is_provisioning', 'ibm_ssh_keys', ['name', 'region', 'cloud_id', 'is_provisioning'], unique=True)
    op.drop_constraint('uix_ibm_ssh_name_region_cloud_id', 'ibm_ssh_keys', type_='unique')
    op.add_column('ibm_security_groups', sa.Column('is_provisioning', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('uix_ibm_security_group_name_vpc_id_region_is_provisioning', 'ibm_security_groups', ['name', 'vpc_id', 'region', 'is_provisioning'], unique=True)
    op.drop_constraint('uix_ibm_security_group_name_vpc_id_region', 'ibm_security_groups', type_='unique')
    op.add_column('ibm_public_gateways', sa.Column('is_provisioning', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('uix_ibm_public_gateway_name_vpc_cloud_id_is_provisioning', 'ibm_public_gateways', ['name', 'vpc_id', 'cloud_id', 'region', 'is_provisioning'], unique=True)
    op.drop_constraint('uix_ibm_public_gateway_name_vpc_cloud_id', 'ibm_public_gateways', type_='unique')
    op.add_column('ibm_network_acls', sa.Column('is_provisioning', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('uix_ibm_acl_name_vpc_region_cloud_id_is_provisioning', 'ibm_network_acls', ['name', 'region', 'vpc_id', 'cloud_id', 'is_provisioning'], unique=True)
    op.drop_constraint('uix_ibm_acl_name_vpc_region_cloud_id', 'ibm_network_acls', type_='unique')
    op.add_column('ibm_load_balancers', sa.Column('is_provisioning', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('uix_ibm_lb_name_vpc_cloud_id_region_is_provisioning', 'ibm_load_balancers', ['name', 'vpc_id', 'cloud_id', 'region', 'is_provisioning'], unique=True)
    op.drop_constraint('uix_ibm_lb_name_vpc_cloud_id_region', 'ibm_load_balancers', type_='unique')
    op.add_column('ibm_ipsec_policy', sa.Column('is_provisioning', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('uix_ibm_ipsec_policy_name_region_cloud_id_is_provisioning', 'ibm_ipsec_policy', ['name', 'region', 'cloud_id', 'is_provisioning'], unique=True)
    op.drop_constraint('uix_ibm_ipsec_policy_name_region_cloud_id', 'ibm_ipsec_policy', type_='unique')
    op.add_column('ibm_instances', sa.Column('is_provisioning', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('uix_ibm_name_vpc_id_cloud_id_region_is_provisioning', 'ibm_instances', ['name', 'vpc_id', 'cloud_id', 'region', 'is_provisioning'], unique=True)
    op.drop_constraint('uix_ibm_name_vpc_id_cloud_id_region', 'ibm_instances', type_='unique')
    op.add_column('ibm_ike_policy', sa.Column('is_provisioning', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('uix_ibm_ike_policy_name_region_cloud_id_is_provisioning', 'ibm_ike_policy', ['name', 'region', 'cloud_id', 'is_provisioning'], unique=True)
    op.drop_constraint('uix_ibm_ike_policy_name_region_cloud_id', 'ibm_ike_policy', type_='unique')
    op.add_column('ibm_address_prefixes', sa.Column('is_provisioning', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('uix_ibm_address_prefix_name_vpc_id_is_provisioning', 'ibm_address_prefixes', ['name', 'vpc_id', 'is_provisioning'], unique=True)
    op.drop_constraint('uix_ibm_address_prefix_name_vpc_id', 'ibm_address_prefixes', type_='unique')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
