"""empty message

Revision ID: cbf2d1a5cd37
Revises: cdd1cac0a1f4
Create Date: 2019-10-07 07:49:24.764746

"""

# revision identifiers, used by Alembic.
revision = 'cbf2d1a5cd37'
down_revision = 'cdd1cac0a1f4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('type', sa.Enum('PRE_BUILT', 'USER_MANAGED'), nullable=False),
    sa.Column('cloud_type', sa.Enum('IBM', 'GCP'), nullable=False),
    sa.Column('schema_type', sa.Enum('VPC', 'INSTANCE', 'ACL', 'SECURITY_GROUP', 'SUBNET'), nullable=False),
    sa.Column('schema', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    # ### end Alembic commands ###