"""empty message

Revision ID: cd4b2d736df0
Revises: c4addc02d3b2
Create Date: 2021-01-26 13:29:44.731101

"""

# revision identifiers, used by Alembic.
revision = 'cd4b2d736df0'
down_revision = 'c4addc02d3b2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_conversion_tasks', sa.Column('retries', sa.Integer(), nullable=True))
    op.alter_column(
        'image_conversion_tasks',
        '_step',
        existing_type=mysql.ENUM(
            'PENDING_PROCESS_START', 'FILES_UPLOADING', 'IMAGE_DOWNLOADING', 'IMAGE_CONVERTING', 'IMAGE_VALIDATING',
            'IMAGE_UPLOADING', 'PENDING_CLEANUP', 'CLEANING_UP', 'PROCESS_COMPLETED'
        ),
        type_=mysql.ENUM(
            'PENDING_PROCESS_START', 'FILES_UPLOADING', 'FILES_UPLOADING_RETRY', 'IMAGE_DOWNLOADING',
            'IMAGE_DOWNLOADING_RETRY', 'IMAGE_CONVERTING', 'IMAGE_VALIDATING', 'IMAGE_UPLOADING', 'PENDING_CLEANUP',
            'CLEANING_UP', 'PROCESS_COMPLETED'
        ),
        existing_nullable=False
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'image_conversion_tasks',
        '_step',
        existing_type=mysql.ENUM(
            'PENDING_PROCESS_START', 'FILES_UPLOADING', 'FILES_UPLOADING_RETRY', 'IMAGE_DOWNLOADING',
            'IMAGE_DOWNLOADING_RETRY', 'IMAGE_CONVERTING', 'IMAGE_VALIDATING', 'IMAGE_UPLOADING', 'PENDING_CLEANUP',
            'CLEANING_UP', 'PROCESS_COMPLETED'
        ),
        type_=mysql.ENUM(
            'PENDING_PROCESS_START', 'FILES_UPLOADING', 'IMAGE_DOWNLOADING', 'IMAGE_CONVERTING', 'IMAGE_VALIDATING',
            'IMAGE_UPLOADING', 'PENDING_CLEANUP', 'CLEANING_UP', 'PROCESS_COMPLETED'
        ),
        existing_nullable=False
    )
    op.drop_column('image_conversion_tasks', 'retries')
    # ### end Alembic commands ###
