"""empty message

Revision ID: cdcfef397d1b
Revises: 6a5f3a18d51c
Create Date: 2020-04-15 08:59:34.828342

"""

# revision identifiers, used by Alembic.
revision = 'cdcfef397d1b'
down_revision = '6a5f3a18d51c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_pool_members', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_pool_members', 'status')
    # ### end Alembic commands ###