"""empty message

Revision ID: cdd1cac0a1f4
Revises: 504480bf9438
Create Date: 2019-09-23 11:51:45.157450

"""

# revision identifiers, used by Alembic.
revision = 'cdd1cac0a1f4'
down_revision = '504480bf9438'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_tasks',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'SUCCESS', 'FAILED'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('config_filename', sa.String(length=36), nullable=False),
    sa.Column('ported_schema', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ibm_subnets', sa.Column('address_prefix_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('ibm_subnet_add_prefix_1', 'ibm_subnets', 'ibm_address_prefixes', ['address_prefix_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ibm_subnet_add_prefix_1', 'ibm_subnets', type_='foreignkey')
    op.drop_column('ibm_subnets', 'address_prefix_id')
    op.drop_table('migration_tasks')
    # ### end Alembic commands ###