"""empty message

Revision ID: d31265178ef3
Revises: 7690148db552
Create Date: 2020-11-03 13:14:30.539824

"""

# revision identifiers, used by Alembic.
revision = 'd31265178ef3'
down_revision = '7690148db552'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_instances', sa.Column('network_attached_storages', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_instances', 'network_attached_storages')
    # ### end Alembic commands ###