"""empty message

Revision ID: d6b7e72c1a61
Revises: ba15fb085111
Create Date: 2019-04-18 12:26:14.427003

"""

# revision identifiers, used by Alembic.
revision = 'd6b7e72c1a61'
down_revision = 'ba15fb085111'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gcp_disks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('disk_type', sa.String(length=255), nullable=False),
    sa.Column('disk_size', sa.String(length=255), nullable=False),
    sa.Column('zone', sa.String(length=255), nullable=False),
    sa.Column('physical_block_size_bytes', sa.String(length=255), nullable=True),
    sa.Column('source_image', sa.String(length=255), nullable=True),
    sa.Column('source_snapshot', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gcp_instances',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('zone', sa.String(length=255), nullable=False),
    sa.Column('machine_type', sa.String(length=255), nullable=False),
    sa.Column('cloud_project_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_project_id'], ['gcp_cloud_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gcp_network_interfaces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('network', sa.String(length=255), nullable=True),
    sa.Column('sub_network', sa.String(length=255), nullable=True),
    sa.Column('primary_internal_ip', sa.String(length=255), nullable=True),
    sa.Column('alias_ip_ranges', sa.String(length=255), nullable=True),
    sa.Column('external_ip', sa.String(length=255), nullable=True),
    sa.Column('instance_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['gcp_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instance_disks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=32), nullable=True),
    sa.Column('disk_id', sa.String(length=32), nullable=True),
    sa.Column('boot', sa.Boolean(), nullable=True),
    sa.Column('auto_delete', sa.Boolean(), nullable=True),
    sa.Column('mode', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['disk_id'], ['gcp_disks.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['gcp_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance_disks')
    op.drop_table('gcp_network_interfaces')
    op.drop_table('gcp_instances')
    op.drop_table('gcp_disks')
    # ### end Alembic commands ###