"""empty message

Revision ID: d87cdc7e9f1b
Revises: 924b390d19e6
Create Date: 2019-10-23 07:40:42.670326

"""

# revision identifiers, used by Alembic.
revision = 'd87cdc7e9f1b'
down_revision = '924b390d19e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_clouds', sa.Column('service_credential', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_clouds', 'service_credential')
    # ### end Alembic commands ###