"""empty message

Revision ID: da7013ac5385
Revises: b07aaf6cbd43
Create Date: 2020-04-23 13:37:43.394835

"""

# revision identifiers, used by Alembic.
revision = 'da7013ac5385'
down_revision = 'b07aaf6cbd43'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'public_key')
    op.drop_column('users', 'private_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('private_key', mysql.VARCHAR(length=2000), nullable=True))
    op.add_column('users', sa.Column('public_key', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###