"""empty message

Revision ID: dd95e3ec614a
Revises: 533866308548
Create Date: 2019-11-25 10:33:02.108417

"""

# revision identifiers, used by Alembic.
revision = 'dd95e3ec614a'
down_revision = '533866308548'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_sub_tasks',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('uix_ibm_address_prefix_name_vpc_id', 'ibm_address_prefixes', ['name', 'vpc_id'])
    op.create_unique_constraint('uix_ibm_floating_ip_name_cloud_id', 'ibm_floating_ips', ['name', 'cloud_id'])
    op.create_unique_constraint('uix_ibm_ike_policy_name_cloud_id', 'ibm_ike_policy', ['name', 'cloud_id'])
    op.create_unique_constraint('uix_ibm_image_name_visibility_cloud_id', 'ibm_images', ['name', 'cloud_id', 'visibility'])
    op.create_unique_constraint('uix_ibm_instance_profile_cloud_id', 'ibm_instance_profiles', ['name', 'cloud_id'])
    op.create_unique_constraint('uix_ibm_name_vpc_id_cloud_id', 'ibm_instances', ['name', 'vpc_id', 'cloud_id'])
    op.create_unique_constraint('uix_ibm_ipsec_policy_name_cloud_id', 'ibm_ipsec_policy', ['name', 'cloud_id'])
    op.create_unique_constraint('uix_ibm_lb_name_vpc_cloud_id', 'ibm_load_balancers', ['name', 'vpc_id', 'cloud_id'])
    op.create_unique_constraint('uix_ibm_acl_name_acl_id', 'ibm_network_acl_rules', ['name', 'acl_id'])
    op.create_unique_constraint('uix_ibm_acl_name_cloud_id', 'ibm_network_acls', ['name', 'cloud_id'])
    op.create_unique_constraint('uix_ibm_interface_name_instance_id', 'ibm_network_interfaces', ['name', 'instance_id'])
    op.create_unique_constraint('uix_ibm_operation_system_name_cloud_id', 'ibm_operating_systems', ['name', 'cloud_id'])
    op.create_unique_constraint('uix_ibm_pool_name_load_balancer_id', 'ibm_pools', ['name', 'load_balancer_id'])
    op.create_unique_constraint('uix_ibm_public_gateway_name_vpc_cloud_id', 'ibm_public_gateways', ['name', 'vpc_id', 'cloud_id'])
    op.create_unique_constraint('uix_ibm_resource_group_name_cloud_id', 'ibm_resource_groups', ['name', 'cloud_id'])
    op.create_unique_constraint('uix_ibm_security_group_name_vpc_id', 'ibm_security_groups', ['name', 'vpc_id'])
    op.create_unique_constraint('uix_ibm_ssh_name_cloud_id', 'ibm_ssh_keys', ['name', 'cloud_id'])
    op.create_unique_constraint('uix_ibm_subnet_name_vpc_id', 'ibm_subnets', ['name', 'vpc_id'])
    op.create_unique_constraint('uix_ibm_volume_name_instance_id', 'ibm_volume_attachments', ['name', 'instance_id'])
    op.add_column('ibm_vpc_networks', sa.Column('action', sa.String(length=50), nullable=True))
    op.add_column('ibm_vpc_networks', sa.Column('message', sa.String(length=300), nullable=True))
    op.create_unique_constraint('uix_ibm_vpc_network_name_cloud_id', 'ibm_vpc_networks', ['name', 'cloud_id'])
    op.create_unique_constraint('uix_ibm_route_name_cloud_id', 'ibm_vpc_routes', ['name', 'vpc_id', 'cloud_id'])
    op.create_unique_constraint('uix_ibm_vpn_connection_name_vpn_gateway_id', 'ibm_vpn_connections', ['name', 'vpn_gateway_id'])
    op.create_unique_constraint('uix_ibm_vpn_gateway_vpc_cloud_id', 'ibm_vpn_gateways', ['name', 'vpc_id', 'cloud_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_ibm_vpn_gateway_vpc_cloud_id', 'ibm_vpn_gateways', type_='unique')
    op.drop_constraint('uix_ibm_vpn_connection_name_vpn_gateway_id', 'ibm_vpn_connections', type_='unique')
    op.drop_constraint('uix_ibm_route_name_cloud_id', 'ibm_vpc_routes', type_='unique')
    op.drop_constraint('uix_ibm_vpc_network_name_cloud_id', 'ibm_vpc_networks', type_='unique')
    op.drop_column('ibm_vpc_networks', 'message')
    op.drop_column('ibm_vpc_networks', 'action')
    op.drop_constraint('uix_ibm_volume_name_instance_id', 'ibm_volume_attachments', type_='unique')
    op.drop_constraint('uix_ibm_subnet_name_vpc_id', 'ibm_subnets', type_='unique')
    op.drop_constraint('uix_ibm_ssh_name_cloud_id', 'ibm_ssh_keys', type_='unique')
    op.drop_constraint('uix_ibm_security_group_name_vpc_id', 'ibm_security_groups', type_='unique')
    op.drop_constraint('uix_ibm_resource_group_name_cloud_id', 'ibm_resource_groups', type_='unique')
    op.drop_constraint('uix_ibm_public_gateway_name_vpc_cloud_id', 'ibm_public_gateways', type_='unique')
    op.drop_constraint('uix_ibm_pool_name_load_balancer_id', 'ibm_pools', type_='unique')
    op.drop_constraint('uix_ibm_operation_system_name_cloud_id', 'ibm_operating_systems', type_='unique')
    op.drop_constraint('uix_ibm_interface_name_instance_id', 'ibm_network_interfaces', type_='unique')
    op.drop_constraint('uix_ibm_acl_name_cloud_id', 'ibm_network_acls', type_='unique')
    op.drop_constraint('uix_ibm_acl_name_acl_id', 'ibm_network_acl_rules', type_='unique')
    op.drop_constraint('uix_ibm_lb_name_vpc_cloud_id', 'ibm_load_balancers', type_='unique')
    op.drop_constraint('uix_ibm_ipsec_policy_name_cloud_id', 'ibm_ipsec_policy', type_='unique')
    op.drop_constraint('uix_ibm_name_vpc_id_cloud_id', 'ibm_instances', type_='unique')
    op.drop_constraint('uix_ibm_instance_profile_cloud_id', 'ibm_instance_profiles', type_='unique')
    op.drop_constraint('uix_ibm_image_name_visibility_cloud_id', 'ibm_images', type_='unique')
    op.drop_constraint('uix_ibm_ike_policy_name_cloud_id', 'ibm_ike_policy', type_='unique')
    op.drop_constraint('uix_ibm_floating_ip_name_cloud_id', 'ibm_floating_ips', type_='unique')
    op.drop_constraint('uix_ibm_address_prefix_name_vpc_id', 'ibm_address_prefixes', type_='unique')
    op.drop_table('ibm_sub_tasks')
    # ### end Alembic commands ###