"""empty message

Revision ID: ecfb13bacca1
Revises: 123169178ee7
Create Date: 2020-02-28 11:34:00.120060

"""

# revision identifiers, used by Alembic.
revision = 'ecfb13bacca1'
down_revision = '123169178ee7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_ibm_volumes_name_region_cloud_id_vol_attachment_id', 'ibm_volumes', ['name', 'region', 'cloud_id', 'volume_attachment_id'])
    op.drop_index('uix_ibm_volumes_name_region_cloud_id', table_name='ibm_volumes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uix_ibm_volumes_name_region_cloud_id', 'ibm_volumes', ['name', 'region', 'cloud_id'], unique=True)
    op.drop_constraint('uix_ibm_volumes_name_region_cloud_id_vol_attachment_id', 'ibm_volumes', type_='unique')
    # ### end Alembic commands ###