"""empty message

Revision ID: f068e2c43cc9
Revises: 3af8bf38d301
Create Date: 2020-07-15 18:39:26.997822

"""

# revision identifiers, used by Alembic.
revision = 'f068e2c43cc9'
down_revision = '3af8bf38d301'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_history')
    # ### end Alembic commands ###
