"""empty message

Revision ID: f1efc4bfca03
Revises: d31265178ef3
Create Date: 2020-11-25 11:04:11.127856

"""

# revision identifiers, used by Alembic.
revision = 'f1efc4bfca03'
down_revision = 'd31265178ef3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_instances_tasks', sa.Column('backup_req_json', sa.JSON(), nullable=True))
    op.add_column('secondary_volume_migration_tasks', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('secondary_volume_migration_tasks', sa.Column('report', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secondary_volume_migration_tasks', 'report')
    op.drop_column('secondary_volume_migration_tasks', 'created_at')
    op.drop_column('ibm_instances_tasks', 'backup_req_json')
    # ### end Alembic commands ###