"""empty message

Revision ID: f469f3e08b2e
Revises: 7db6ab491f70
Create Date: 2019-10-25 10:45:10.463213

"""

# revision identifiers, used by Alembic.
revision = 'f469f3e08b2e'
down_revision = '7db6ab491f70'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_operating_systems',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('architecture', sa.String(length=255), nullable=True),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ibm_images', sa.Column('image_template_path', sa.String(length=255), nullable=True))
    op.add_column('ibm_images', sa.Column('operating_system_id', sa.String(length=32), nullable=True))
    op.add_column('ibm_images', sa.Column('region', sa.String(length=255), nullable=True))
    op.add_column('ibm_images', sa.Column('resource_group_id', sa.String(length=32), nullable=True))
    op.add_column('ibm_images', sa.Column('size', sa.String(length=255), nullable=True))
    op.add_column('ibm_images', sa.Column('status', sa.String(length=50), nullable=False))
    op.create_foreign_key('ibm_images_rg_fkey1', 'ibm_images', 'ibm_resource_groups', ['resource_group_id'], ['id'])
    op.create_foreign_key('ibm_images_os_fkey1', 'ibm_images', 'ibm_operating_systems', ['operating_system_id'], ['id'])
    op.drop_column('ibm_images', 'os_version')
    op.drop_column('ibm_images', 'os_vendor')
    op.drop_column('ibm_images', 'os_name')
    op.drop_column('ibm_images', 'architecture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_images', sa.Column('architecture', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('ibm_images', sa.Column('os_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('ibm_images', sa.Column('os_vendor', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('ibm_images', sa.Column('os_version', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint('ibm_images_os_fkey1', 'ibm_images', type_='foreignkey')
    op.drop_constraint('ibm_images_rg_fkey1', 'ibm_images', type_='foreignkey')
    op.drop_column('ibm_images', 'status')
    op.drop_column('ibm_images', 'size')
    op.drop_column('ibm_images', 'resource_group_id')
    op.drop_column('ibm_images', 'region')
    op.drop_column('ibm_images', 'operating_system_id')
    op.drop_column('ibm_images', 'image_template_path')
    op.drop_table('ibm_operating_systems')
    # ### end Alembic commands ###