"""empty message

Revision ID: f7a6326f8d96
Revises: 3dd18334c775
Create Date: 2021-09-19 04:16:51.530638

"""

# revision identifiers, used by Alembic.
revision = 'f7a6326f8d96'
down_revision = '3dd18334c775'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kubernetes_cluster_migration_tasks',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('base_task_id', sa.String(length=32), nullable=False),
    sa.Column('source_cluster', sa.JSON(), nullable=True),
    sa.Column('target_cluster', sa.JSON(), nullable=True),
    sa.Column('cos', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kubernetes_clusters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pod_subnet', sa.String(length=255), nullable=True),
    sa.Column('service_subnet', sa.String(length=255), nullable=True),
    sa.Column('kube_version', sa.String(length=255), nullable=False),
    sa.Column('disable_public_service_endpoint', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('cluster_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('workloads', sa.JSON(), nullable=True),
    sa.Column('resource_group_id', sa.String(length=32), nullable=True),
    sa.Column('vpc_id', sa.String(length=32), nullable=False),
    sa.Column('cloud_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cloud_id'], ['ibm_clouds.id'], ),
    sa.ForeignKeyConstraint(['resource_group_id'], ['ibm_resource_groups.id'], ),
    sa.ForeignKeyConstraint(['vpc_id'], ['ibm_vpc_networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kubernetes_cluster_worker_pools',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('disk_encryption', sa.Boolean(), nullable=False),
    sa.Column('flavor', sa.String(length=255), nullable=False),
    sa.Column('worker_count', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('kubernetes_cluster_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['kubernetes_cluster_id'], ['kubernetes_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kubernetes_cluster_worker_pool_zones',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('private_vlan', sa.String(length=255), nullable=True),
    sa.Column('worker_pool_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['worker_pool_id'], ['kubernetes_cluster_worker_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classic_kubernetes_zone_subnets',
    sa.Column('zone_id', sa.String(length=32), nullable=False),
    sa.Column('subnets_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['subnets_id'], ['ibm_subnets.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['kubernetes_cluster_worker_pool_zones.id'], ),
    sa.PrimaryKeyConstraint('zone_id', 'subnets_id')
    )
    op.add_column('ibm_service_credentials', sa.Column('access_key_id', sa.String(length=500), nullable=True))
    op.add_column('ibm_service_credentials', sa.Column('secret_access_key', sa.String(length=500), nullable=True))
    op.add_column('softlayer_clouds', sa.Column('ibm_cloud_account_id', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('softlayer_clouds', 'ibm_cloud_account_id')
    op.drop_column('ibm_service_credentials', 'secret_access_key')
    op.drop_column('ibm_service_credentials', 'access_key_id')
    op.drop_table('classic_kubernetes_zone_subnets')
    op.drop_table('kubernetes_cluster_worker_pool_zones')
    op.drop_table('kubernetes_cluster_worker_pools')
    op.drop_table('kubernetes_clusters')
    op.drop_table('kubernetes_cluster_migration_tasks')
    # ### end Alembic commands ###
