"""empty message

Revision ID: f8a4fc6ff994
Revises: 2a813854387a
Create Date: 2020-01-16 10:29:31.291922

"""

# revision identifiers, used by Alembic.
revision = 'f8a4fc6ff994'
down_revision = '2a813854387a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_ibm_acl_name_region_cloud_id', 'ibm_network_acls', ['name', 'region', 'cloud_id'])
    op.drop_index('uix_ibm_acl_name_cloud_id', table_name='ibm_network_acls')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uix_ibm_acl_name_cloud_id', 'ibm_network_acls', ['name', 'cloud_id'], unique=True)
    op.drop_constraint('uix_ibm_acl_name_region_cloud_id', 'ibm_network_acls', type_='unique')
    # ### end Alembic commands ###
