"""empty message

Revision ID: f94bd2833bf0
Revises: 221e593870bd
Create Date: 2019-11-07 07:50:35.937706

"""

# revision identifiers, used by Alembic.
revision = 'f94bd2833bf0'
down_revision = '221e593870bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_vpc_networks', sa.Column('address_prefix_management', sa.Enum('auto', 'manual'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_vpc_networks', 'address_prefix_management')
    # ### end Alembic commands ###