"""empty message

Revision ID: fa0aafff5df2
Revises: 9862a399a35c
Create Date: 2020-05-04 16:20:56.148477

"""

# revision identifiers, used by Alembic.
revision = 'fa0aafff5df2'
down_revision = '9862a399a35c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibm_volumes', sa.Column('original_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibm_volumes', 'original_capacity')
    # ### end Alembic commands ###
