"""empty message

Revision ID: fa690c8fb4e3
Revises: a30ef4b6c469
Create Date: 2019-12-18 06:53:41.839110

"""

# revision identifiers, used by Alembic.
revision = 'fa690c8fb4e3'
down_revision = 'a30ef4b6c469'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('softlayer_clouds',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('softlayer_clouds')
    # ### end Alembic commands ###