LIST_NETWORK_ACLS_PATH = "network_acls"
CREATE_NETWORK_ACL_PATH = "network_acls"
DELETE_NETWORK_ACL_PATH = "network_acls/{network_acl_id}"
GET_NETWORK_ACL_PATH = "network_acls/{network_acl_id}"
UPDATE_NETWORK_ACL_PATH = "network_acls/{network_acl_id}"

LIST_NETWORK_ACL_RULES_PATH = "network_acls/{network_acl_id}/rules"
CREATE_NETWORK_ACL_RULE_PATH = "network_acls/{network_acl_id}/rules"
DELETE_NETWORK_ACL_RULE_PATH = "network_acls/{network_acl_id}/rules/{rule_id}"
GET_NETWORK_ACL_RULE_PATH = "network_acls/{network_acl_id}/rules/{rule_id}"
UPDATE_NETWORK_ACL_RULE_PATH = "network_acls/{network_acl_id}/rules/{rule_id}"
