LIST_LOAD_BALANCERS_PATH = "load_balancers"
CREATE_LOAD_BALANCER_PATH = "load_balancers"
DELETE_LOAD_BALANCER_PATH = "load_balancers/{load_balancer_id}"
GET_LOAD_BALANCER_PATH = "load_balancers/{load_balancer_id}"
UPDATE_LOAD_BALANCER_PATH = "load_balancers/{load_balancer_id}"

LIST_LOAD_BALANCER_LISTENERS_PATH = "load_balancers/{load_balancer_id}/listeners"
CREATE_LOAD_BALANCER_LISTENER_PATH = "load_balancers/{load_balancer_id}/listeners"
DELETE_LOAD_BALANCER_LISTENER_PATH = "load_balancers/{load_balancer_id}/listeners/{listener_id}"
GET_LOAD_BALANCER_LISTENER_PATH = "load_balancers/{load_balancer_id}/listeners/{listener_id}"
UPDATE_LOAD_BALANCER_LISTENER_PATH = "load_balancers/{load_balancer_id}/listeners/{listener_id}"

LIST_LOAD_BALANCER_LISTENER_POLICIES_PATH = "load_balancers/{load_balancer_id}/listeners/{listener_id}/policies"

LIST_LOAD_BALANCER_POOLS_PATH = "load_balancers/{load_balancer_id}/pools"
CREATE_LOAD_BALANCER_POOL_PATH = "load_balancers/{load_balancer_id}/pools"
DELETE_LOAD_BALANCER_POOL_PATH = "load_balancers/{load_balancer_id}/pools/{pool_id}"
GET_LOAD_BALANCER_POOL_PATH = "load_balancers/{load_balancer_id}/pools/{pool_id}"
UPDATE_LOAD_BALANCER_POOL_PATH = "load_balancers/{load_balancer_id}/pools/{pool_id}"

LIST_LOAD_BALANCER_POOL_MEMBERS_PATH = "load_balancers/{load_balancer_id}/pools/{pool_id}/members"
CREATE_LOAD_BALANCER_POOL_MEMBER_PATH = "load_balancers/{load_balancer_id}/pools/{pool_id}/members"
DELETE_LOAD_BALANCER_POOL_MEMBER_PATH = "load_balancers/{load_balancer_id}/pools/{pool_id}/members/{member_id}"
GET_LOAD_BALANCER_POOL_MEMBER_PATH = "load_balancers/{load_balancer_id}/pools/{pool_id}/members/{member_id}"
UPDATE_LOAD_BALANCER_POOL_MEMBER_PATH = "load_balancers/{load_balancer_id}/pools/{pool_id}/members/{member_id}"
UPDATE_LOAD_BALANCER_POOL_MEMBERS_PATH = "load_balancers/{load_balancer_id}/pools/{pool_id}/members"
