apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: hna:latest
        ports:
        - containerPort: 80
      livenessProbe:
      exec:
        command:
        - cat
        - /healthcheck
      initialDelaySeconds: 5
      periodSeconds: 15
      failureThreshold: 1
