apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-2
spec:
  selector:
    matchLabels:
      app: myapp2
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: myapp2
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
