VPC_MAJOR_VERSION = "v1"
VPC_DATE_BASED_VERSION = "2021-05-18"
VSI_FIXED_DATE_BASED_VERSION = "2021-08-10"
VPC_GENERATION = "2"
VPC_RESOURCE_REQUIRED_PARAMS = {
    "version": VPC_DATE_BASED_VERSION,
    "generation": VPC_GENERATION
}
VPC_DEFAULT_REGION = "us-south"
VPC_DEFAULT_PAGINATION_LIMIT = 100

RESOURCE_MANAGER_MAJOR_VERSION = "v2"
