name: Temporary Comment

on: [push]

jobs:
  temporary-comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Comment Makefile
      run: |
        sed -i "${1}s/^/# /" file.txt
        sed -i "${2}s/^/# /" file.txt
 


