name: Temporary Comment

on: [push]

jobs:
  temporary-comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add temporary comment
      run: |
        echo "This is a temporary comment" >> file.txt
    - name: Commit and push change
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add file.txt
        git commit -m "Add temporary comment"
        git push origin main
    - name: Revert change
      run: |
        git checkout HEAD -- file.txt
        git commit -m "Revert temporary comment"
        git push origin main
