name: Temporary Comment

on: [push]

jobs:
  temporary-comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add temporary comment
      run: |
        echo "This is a temporary comment" >> file.txt
    - name: Stage changes
      run: |
        git config --global user.email "humayun@wanclouds.net"
        git config --global user.name "HumayunNasir23"
        git add file.txt
    - name: Reset change
    - run: git reset file.txt

