name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.ref"  
      - run: echo "Deploy on production"
        if: github.ref == 'refs/heads/develop'
      - run: echo "Hey There if is not working"
      - run: echo "Oh NO!!!!!"
        if: github.ref == 'refs/heads/main'
      - run: echo "Hey There if is working successfully!!!"
      - run: echo "YESSSSSSSS !!!!!"
      
  develop-deploy:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.ref"  
      - run: echo "Deploy on develop"    
