name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.ref"  
      - run: echo "Deploy on production" 
  develop-deploy:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.ref"  
      - run: echo "Deploy on develop"    
      
