
name: GitHub Actions Demo
on: 
  push:
    branches: [ main ]
jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Deploy to Dev
      run: echo "Dev deployment"

 

